### ISSUE TITLE
Freeze in lws_plat_pipe_signal with external epoll loop

### ISSUE THREAD

**Issue by livrrr** [warmcat/libwebsockets#1233]
Hello.
I want to use websocket server with external epoll loop.
My main loop is based on test-server.c example and callback code is based on test-server-http.c example.
I want to service more than 20 000 clients.
But my application some times freezes while accepting new client connections (it freezes only with 15000+ client connections) with such stack trace (I have already try to use Edge Triggered and Level Triggered epoll behavior):
```
#0  0x00007f70e76ef210 in __write_nocancel () from /lib64/libpthread.so.0
#1  0x00007f70e72c1277 in lws_plat_pipe_signal (wsi=wsi@entry=0x1e7ee90) at /home/roma/EclipseProjects/libwebsockets/lib/plat/lws-plat-unix.c:53
#2  0x00007f70e72b4b35 in lws_cancel_service_pt (wsi=wsi@entry=0x1e7ee90) at /home/roma/EclipseProjects/libwebsockets/lib/context.c:929
#3  0x00007f70e72c34ba in lws_adopt_descriptor_vhost (vh=0x97dae0, type=<optimized out>, fd=..., fd@entry=..., vh_prot_name=vh_prot_name@entry=0x0, 
    parent=parent@entry=0x0) at /home/roma/EclipseProjects/libwebsockets/lib/server/server.c:2251
#4  0x00007f70e72c3d53 in lws_server_socket_service (context=context@entry=0x97c800, wsi=wsi@entry=0x97dd40, pollfd=pollfd@entry=0x7ffe61ac3678)
    at /home/roma/EclipseProjects/libwebsockets/lib/server/server.c:2816
#5  0x00007f70e72adbad in lws_service_fd_tsi (context=<optimized out>, pollfd=pollfd@entry=0x7ffe61ac3678, tsi=tsi@entry=0)
    at /home/roma/EclipseProjects/libwebsockets/lib/service.c:1521
#6  0x00007f70e72ae287 in lws_service_fd (context=<optimized out>, pollfd=pollfd@entry=0x7ffe61ac3678)
    at /home/roma/EclipseProjects/libwebsockets/lib/service.c:1962
#7  0x0000000000432146 in ModuleWSEpollServerMVP::fetch (this=0x961270) at modulesrc/moduleWSEpollServerMVP.cpp:683
#8  0x000000000041f6f2 in ModuleFather::fetch (this=this@entry=0x7ffe61ac37d0) at modulesrc/moduleFather.cpp:302
#9  0x0000000000404111 in main (argc=<optimized out>, argv=0x7ffe61ac39e8) at main.cpp:118
```

and I can not understand why. When I use external poll loop from library's examples I have no freezes, but I have low performance with such amount of clients.

Here are critical parts of my code (I can publish all code, but it is rather large):
```
#ifdef EXTERNAL_EPOLL
int _efd; // epoll descriptor
struct epoll_event *_events; // triggered events
int _events_size_max;
#endif

static int epoll_from_poll(int e)
{
    int res = 0;
    if (e & POLLIN)
    {
        res |= (EPOLLIN);// | EPOLLET);
    }
    if (e & POLLOUT)
    {
        res |= EPOLLOUT;
    }
    if (e & POLLPRI)
    {
        res |= EPOLLPRI;
    }
    if (e & POLLERR)
    {
        res |= EPOLLERR;
    }
    if (e & POLLHUP)
    {
        res |= EPOLLHUP;
    }
    if (e & POLLRDHUP)
    {
        res |= EPOLLRDHUP;
    }
    if (e & POLLRDNORM)
    {
        res |= (EPOLLRDNORM);// | EPOLLET);
    }
    if (e & POLLRDBAND)
    {
        res |= EPOLLRDBAND;
    }
    if (e & POLLWRNORM)
    {
        res |= EPOLLWRNORM;
    }
    if (e & POLLWRBAND)
    {
        res |= EPOLLWRBAND;
    }
    if (e & POLLMSG)
    {
        res |= EPOLLMSG;
    }
    return res;
}

static int poll_from_epoll(int e)
{
    int res = 0;
    if (e & EPOLLIN)
    {
        res |= POLLIN;
    }
    if (e & EPOLLOUT)
    {
        res |= POLLOUT;
    }
    if (e & EPOLLPRI)
    {
        res |= POLLPRI;
    }
    if (e & EPOLLERR)
    {
        res |= POLLERR;
    }
    if (e & EPOLLHUP)
    {
        res |= POLLHUP;
    }
    if (e & EPOLLRDHUP)
    {
        res |= POLLRDHUP;
    }
    if (e & EPOLLRDNORM)
    {
        res |= POLLRDNORM;
    }
    if (e & EPOLLRDBAND)
    {
        res |= POLLRDBAND;
    }
    if (e & EPOLLWRNORM)
    {
        res |= POLLWRNORM;
    }
    if (e & EPOLLWRBAND)
    {
        res |= POLLWRBAND;
    }
    if (e & EPOLLMSG)
    {
        res |= POLLMSG;
    }
    return res;
}

static int callback_mvs(
    struct lws *wsi, 
    enum lws_callback_reasons reason, 
    void *user, 
    void *in, 
    size_t len)
{
...
#ifdef EXTERNAL_EPOLL
    case LWS_CALLBACK_ADD_POLL_FD:
    {
        lws_pollargs* pa = (lws_pollargs*) in;
        //LOG_INFO << "add " << pa->fd << ' ' << (pa->events)<< FLUSH;
        struct epoll_event event;
        event.data.fd = pa->fd;
        event.events = epoll_from_poll(pa->events);
        if (epoll_ctl (_efd, EPOLL_CTL_ADD, pa->fd, &event) == -1)
        {
            perror ("epoll_ctl_add");
            abort ();
        }
        break;
    }
    case LWS_CALLBACK_DEL_POLL_FD:
    {
        lws_pollargs* pa = (lws_pollargs*) in;
        //LOG_INFO << "del " << pa->fd << ' ' << (pa->events)<< FLUSH;
        struct epoll_event event;
        event.data.fd = pa->fd;
        if (epoll_ctl (_efd, EPOLL_CTL_DEL, pa->fd, &event) == -1)
        {
            perror ("epoll_ctl_del");
            abort ();
        }
        close(pa->fd);
        break;
    }
    case LWS_CALLBACK_CHANGE_MODE_POLL_FD:
    {
        lws_pollargs* pa = (lws_pollargs*) in;
        //LOG_INFO << "mod " << pa->fd << ' ' << (pa->events) << ' ' << (pa->prev_events) << FLUSH;
        struct epoll_event event;
        event.data.fd = pa->fd;
        event.events = epoll_from_poll(pa->events);
        if (epoll_ctl (_efd, EPOLL_CTL_MOD, pa->fd, &event) == -1)
        {
            perror ("epoll_ctl_mod");
            abort ();
        }
        break;
    }
#endif
...
}

int main()
{
...
#ifdef EXTERNAL_EPOLL
    _efd = epoll_create1 (0);
    if (_efd == -1) {
        perror ("epoll_create");
        abort ();
    }
    _last_lws_check = 0;
    
    _events_size_max = 65536;

    /* Buffer where events are returned */
    _events = (epoll_event*) malloc (_events_size_max * sizeof(epoll_event));
    memset(_events, _events_size_max * sizeof(epoll_event), '0');
#endif
...

    while (true)
    {
#ifdef EXTERNAL_EPOLL
    int n = epoll_wait (_efd, _events, _events_size_max, 0);
    if (n < 0)
    {
        // err???
        return;
    }
    if (n)
    {
        for (int i = 0; i < n; i++)
        {
            lws_pollfd p;
            p.fd = _events[i].data.fd;
            p.events = poll_from_epoll(_events[i].events);
            p.revents = p.events;
            lws_service_fd(_context, &p);
        }
        while (!lws_service_adjust_timeout(_context, 1, 0))
        {
            lwsl_notice("extpoll doing forced service!\n");
            lws_service_tsi(_context, -1, 0);
        }
    }
    //else
    {
        unsigned long long t = get_msec_date_time();
        if (_last_lws_check + 1000 < t)
        {
            lwsl_notice("1 per sec\n");
            lws_service_fd(_context, NULL);
            _last_lws_check = t;
        }
    }
#endif
    }
...
}
```

**Comment by lws-team** [comment]
Hmmm "freeze" is almost always the wrong word.

You are blocking there are you?  ie, 0% CPU?

Try this  (but it is against master, the pipe read code has moved around)

```
diff --git a/lib/plat/lws-plat-unix.c b/lib/plat/lws-plat-unix.c
index 6b8eff88..bac4090c 100644
--- a/lib/plat/lws-plat-unix.c
+++ b/lib/plat/lws-plat-unix.c
@@ -40,7 +40,7 @@ lws_plat_pipe_create(struct lws *wsi)
 {
        struct lws_context_per_thread *pt = &wsi->context->pt[(int)wsi->tsi];
 
-       return pipe(pt->dummy_pipe_fds);
+       return pipe2(pt->dummy_pipe_fds, O_NONBLOCK);
 }
 
 int
diff --git a/lib/roles/pipe/ops-pipe.c b/lib/roles/pipe/ops-pipe.c
index aaccb5b5..f18e65ce 100644
--- a/lib/roles/pipe/ops-pipe.c
+++ b/lib/roles/pipe/ops-pipe.c
@@ -26,7 +26,7 @@ rops_handle_POLLIN_pipe(struct lws_context_per_thread *pt, struct lws *wsi,
                        struct lws_pollfd *pollfd)
 {
 #if !defined(WIN32) && !defined(_WIN32)
-       char s[10];
+       char s[50];
        int n;
 
        /*
```

**Comment by livrrr** [comment]
Of course, you are right, "freeze" is a wrong word.
Program is blocking there and use 0% CPU.
Thank you, now I have no blocks on write calls using external epoll loop.
