### ISSUE TITLE
Crash in libwebsockets-test-client

### ISSUE THREAD

**Issue by bqv** [warmcat/libwebsockets#1262]
Steps to reproduce:

Connect to `wss://cerberus-xxxx.lb.slack-msgs.com:443/websocket/gcuuK1YUM-0bhbJ98hYqVKwg1Q7sY5QWu83CZbmkwfccbSI7lma6oLrel9ARWjWvlsJDmHyzbBUWGw-Z6lN0LDAh8sTsuZtG2pypSmBRf5ZVngswAalbyLIoeRuSVQ15rx4WPL1A0TnwzbIK/2`

Backtrace:

```#0  __strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:31
#1  0x0000555555566a43 in lws_role_call_alpn_negotiated (wsi=0x5555557bb830, alpn=0x7fffffffcdc0 "") at ./libwebsockets/lib/context.c:70
#2  0x000055555557cea9 in lws_tls_client_connect (wsi=0x5555557bb830) at ./libwebsockets/lib/tls/openssl/openssl-client.c:252
#3  0x000055555557c4ea in lws_ssl_client_connect2 (wsi=0x5555557bb830, errbuf=0x7fffffffce70 "", len=128) at ./libwebsockets/lib/tls/tls-client.c:60
#4  0x0000555555574ad5 in lws_client_socket_service (wsi=0x5555557bb830, pollfd=0x555555798e38, wsi_conn=0x0) at ./libwebsockets/lib/roles/http/client/client.c:326
#5  0x000055555556dc0c in rops_handle_POLLIN_h1 (pt=0x5555557965c8, wsi=0x5555557bb830, pollfd=0x555555798e38) at ./libwebsockets/lib/roles/h1/ops-h1.c:556
#6  0x0000555555564760 in lws_service_fd_tsi (context=0x555555796530, pollfd=0x555555798e38, tsi=0) at ./libwebsockets/lib/service.c:855
#7  0x000055555557eddb in _lws_plat_service_tsi (context=0x555555796530, timeout_ms=500, tsi=0) at ./libwebsockets/lib/plat/lws-plat-unix.c:297
#8  0x000055555557ee66 in lws_plat_service (context=0x555555796530, timeout_ms=500) at ./libwebsockets/lib/plat/lws-plat-unix.c:319
#9  0x0000555555564838 in lws_service (context=0x555555796530, timeout_ms=500) at ./libwebsockets/lib/service.c:902
#10 0x000055555555ddf8 in main (argc=2, argv=0x7fffffffe358) at ./libwebsockets/test-apps/test-client.c:821
```

Verdict:

https://github.com/warmcat/libwebsockets/blob/master/lib/roles/ws/ops-ws.c#L1963 should this really be NULL? Should it not be an empty string?

**Comment by bqv** [comment]
Fix:

```c
diff --git a/lib/context.c b/lib/context.c
index 6474f475..7160421b 100644
--- a/lib/context.c
+++ b/lib/context.c
@@ -67,7 +67,7 @@ lws_role_call_alpn_negotiated(struct lws *wsi, const char *alpn)
        lwsl_info("%s: '%s'\n", __func__, alpn);

        LWS_FOR_EVERY_AVAILABLE_ROLE_START(ar)
-               if (!strcmp(ar->alpn, alpn) && ar->alpn_negotiated)
+               if (ar->alpn && !strcmp(ar->alpn, alpn) && ar->alpn_negotiated)
                        return ar->alpn_negotiated(wsi, alpn);
        LWS_FOR_EVERY_AVAILABLE_ROLE_END;
 #endif
```

**Comment by lws-team** [comment]
Thanks, it's pushed on master.
