### ISSUE TITLE
lws_client_connect_2--got segmentation fault

### ISSUE THREAD

**Issue by lhlonng** [warmcat/libwebsockets#1410]
Hi:
 app get  segmentation fault while lws_client_connect_2 is invoked, and the host is localhost.(if i using 127.0.0.1 instead of localhost, the app could run success).
log : [2018/09/12 11:37:53:2973] INFO: Initial logging level 1471
[2018/09/12 11:37:53:3007] INFO: Libwebsockets version: 3.0.1 unknown-build-hash
[2018/09/12 11:37:53:3043] INFO: IPV6 compiled in and enabled
[2018/09/12 11:37:53:3119] INFO:  LWS_DEF_HEADER_LEN    : 4096
[2018/09/12 11:37:53:3151] INFO:  LWS_MAX_PROTOCOLS     : 5
[2018/09/12 11:37:53:3185] INFO:  LWS_MAX_SMP           : 1
[2018/09/12 11:37:53:3200] INFO:  sizeof (*info)        : 296
[2018/09/12 11:37:53:3203] INFO:  SYSTEM_RANDOM_FILEPATH: '/dev/urandom'
[2018/09/12 11:37:53:3206] INFO:  HTTP2 support         : not configured
[2018/09/12 11:37:53:3209] DEBUG: _realloc: size 560: context
[2018/09/12 11:37:53:3212] INFO: Using event loop: poll
[2018/09/12 11:37:53:3214] INFO: Default ALPN advertisment: http/1.1
[2018/09/12 11:37:53:3217] INFO:  default timeout (secs): 20
[2018/09/12 11:37:53:3219] DEBUG: _realloc: size 4096: pt_serv_buf
[2018/09/12 11:37:53:3222] INFO:  Threads: 1 each 1024 fds
[2018/09/12 11:37:53:3225] INFO:  mem: context:          4656 B (560 ctx + (1 thr x 4096))
[2018/09/12 11:37:53:3228] INFO:  mem: http hdr rsvd:   5152768 B (1 thr x (4096 + 936) x 1024))
[2018/09/12 11:37:53:3230] DEBUG: _realloc: size 8192: fds table
[2018/09/12 11:37:53:3234] INFO:  mem: pollfd map:       8192
[2018/09/12 11:37:53:3237] DEBUG: _realloc: size 4096: lws_lookup
[2018/09/12 11:37:53:3240] INFO:  mem: platform fd map:  4096 bytes
[2018/09/12 11:37:53:3243] DEBUG: _realloc: size 304: event pipe wsi
[2018/09/12 11:37:53:3246] DEBUG: lws_role_transition: 0x825dc0: wsistate 0x200, ops pipe
[2018/09/12 11:37:53:3249] DEBUG: event pipe fd 6
[2018/09/12 11:37:53:3252] DEBUG: __insert_wsi_socket_into_fds: 0x825dc0: tsi=0, sock=6, pos-in-fds=0
[2018/09/12 11:37:53:3254] INFO:  Compiled with OpenSSL support
[2018/09/12 11:37:53:3257] INFO:  SSL disabled: no LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT
[2018/09/12 11:37:53:3260] DEBUG: _realloc: size 504: create vhost
[2018/09/12 11:37:53:3262] DEBUG: _realloc: size 56: vhost-specific plugin table
[2018/09/12 11:37:53:3265] DEBUG: _realloc: size 4: same vh list
[2018/09/12 11:37:53:3268] NOTICE: Creating Vhost 'default' (serving disabled), 1 protocols, IPv6 on
[2018/09/12 11:37:53:3271] INFO:  mem: per-conn:          304 bytes + protocol rx buf
[2018/09/12 11:37:53:3274] INFO:  canonical_hostname = Gogenius
[2018/09/12 11:37:53:3276] INFO: lws_cancel_service
[2018/09/12 11:37:53:3782] INFO: lws_protocol_init
[2018/09/12 11:37:55:3277] DEBUG: _realloc: size 304: client wsi
[2018/09/12 11:37:55:3279] DEBUG: lws_role_transition: 0x8261c0: wsistate 0x10000200, ops h1
[2018/09/12 11:37:55:3280] DEBUG: _realloc: size 180: client ws struct
[2018/09/12 11:37:55:3282] DEBUG: lws_role_transition: 0x8261c0: wsistate 0x10000200, ops h1
[2018/09/12 11:37:55:3283] DEBUG: _realloc: size 32: client stash
[2018/09/12 11:37:55:3285] DEBUG: _realloc: size 10: strdup
[2018/09/12 11:37:55:3286] DEBUG: _realloc: size 2: strdup
[2018/09/12 11:37:55:3288] DEBUG: _realloc: size 15: strdup
[2018/09/12 11:37:55:3289] DEBUG: _realloc: size 15: strdup
[2018/09/12 11:37:55:3291] DEBUG: _realloc: size 9: strdup
[2018/09/12 11:37:55:3292] INFO: lws_header_table_attach: wsi 0x8261c0: ah (nil) (tsi 0, count = 0) in
[2018/09/12 11:37:55:3294] DEBUG: _realloc: size 936: ah struct
[2018/09/12 11:37:55:3305] DEBUG: _realloc: size 4096: ah data
[2018/09/12 11:37:55:3350] INFO: _lws_create_ah: created ah 0x85de90 (size 4096): pool length 1
[2018/09/12 11:37:55:3383] INFO: lws_header_table_attach: did attach wsi 0x8261c0: ah 0x85de90: count 1 (on exit)
[2018/09/12 11:37:55:3399] DEBUG: __lws_set_timeout: 0x8261c0: 10 secs
[2018/09/12 11:37:55:3400] CLIENT: lws_client_connect_2: 0x8261c0
[2018/09/12 11:37:55:3402] DEBUG: _realloc: size 10: strdup
[2018/09/12 11:37:55:3403] INFO: lws_client_connect_2: 0x8261c0: address localhost
Segmentation fault

**Comment by lws-team** [comment]
Okay... "it crashes" or "it segfaults" is usually completely useless to me.

Please run it under gdb or some other platform and get a backtrace so we can get a clue where the problem is and maybe why... it looks like you are already building in debug mode so it should be easy.  On *nix / gcc it is like

```
 $ gdb --ex r --args myapp
```

any args that your app needs can go after "myapp".

**Comment by lhlonng** [comment]
Hi:

information as follows：

env:
```
cpu arch: mips (mt7688)
kernel version:3.18.23
system: openwrt
```

connect function:
```
static struct lws *connect_server(lwsCtrlDef *lwsCtrl)
{
    struct lws_client_connect_info info;
    char host[128];
    memset(&info, 0, sizeof(info));
    snprintf(host, sizeof(host), "%s:%u", HOST_ADDRESS, HOST_PORT);
    info.context = lwsCtrl->ctx;
    info.port = HOST_PORT;          // "localhost"
    info.address = HOST_ADDRESS;    // 2324
    info.path = "/";
    info.host = host;
    info.origin = host;
    /*info.ssl_connection = 0;*/
    info.userdata = lwsCtrl;
    info.pwsi = &client_wsi;
    return lws_client_connect_via_info(&info);
}
```

protocols：
```
static struct lws_protocols protocols[] = {
    {
        PROTOCOL_NAME,
        callbackForClient,
        0,
        102400,
        0,
        NULL,
        0

    },
    { NULL, NULL, 0, 0  } /* terminator */
};
```
context create:
```
struct lws_context_creation_info info;

    memset(&info, 0, sizeof(info));
    info.port = CONTEXT_PORT_NO_LISTEN;
    info.protocols = protocols;
    info.gid = -1;
    info.uid = -1;

    lws_set_log_level(logs, NULL);

    lwsCtrl.ctx = lws_create_context(&info);

```
gdb debug info:
```

tomato@Base:~$ ./staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mipsel-openwrt-linux-gdb build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/lwsApp/lwsApp lwsApp.2613.11.1536728860.core
Python Exception <type 'exceptions.ImportError'> No module named gdb:

warning:
Could not load the Python gdb module from `/home/tomato/Project/Single_mt7688/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/share/gdb/python'.
Limited Python support is available from the _gdb module.
Suggest passing --data-directory=/path/to/gdb/data-directory.

GNU gdb (Linaro GDB) 7.6-2013.05
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=x86_64-linux-gnu --target=mipsel-openwrt-linux-uclibc".
For bug reporting instructions, please see:
<http://bugs.launchpad.net/gdb-linaro/>...
Reading symbols from /home/tomato/Project/Single_mt7688/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/lwsApp/lwsApp...done.
[New LWP 2613]

warning: Could not load shared library symbols for 14 libraries, e.g. /usr/lib/libzlog.so.
Use the "info sharedlibrary" command to see the complete listing.
Do you need "set solib-search-path" or "set sysroot"?
Core was generated by `lwsApp'.
Program terminated with signal 11, Segmentation fault.
#0  0x76ff33b8 in ?? ()
(gdb) set solib-search-path staging_dir/
host/                                                      toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/
target-mipsel_24kec+dsp_uClibc-0.9.33.2/                   toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/
(gdb) set solib-search-path staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib/
Reading symbols from /home/tomato/Project/Single_mt7688/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib/libzlog.so...done.
Loaded symbols for /home/tomato/Project/Single_mt7688/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib/libzlog.so
Reading symbols from /home/tomato/Project/Single_mt7688/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib/libubus.so...done.
Loaded symbols for /home/tomato/Project/Single_mt7688/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib/libubus.so
Reading symbols from /home/tomato/Project/Single_mt7688/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib/libubox.so...done.
Loaded symbols for /home/tomato/Project/Single_mt7688/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib/libubox.so
Reading symbols from /home/tomato/Project/Single_mt7688/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib/libjson-c.so.2.0.1...(no debugging symbols found)...done.
Loaded symbols for /home/tomato/Project/Single_mt7688/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib/libjson-c.so.2.0.1
Reading symbols from /home/tomato/Project/Single_mt7688/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib/libwebsockets.so.13...done.
Loaded symbols for /home/tomato/Project/Single_mt7688/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib/libwebsockets.so.13
Reading symbols from /home/tomato/Project/Single_mt7688/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib/libssl.so.1.0.0...(no debugging symbols found)...done.
Loaded symbols for /home/tomato/Project/Single_mt7688/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib/libssl.so.1.0.0
Reading symbols from /home/tomato/Project/Single_mt7688/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib/libcrypto.so.1.0.0...(no debugging symbols found)...done.
Loaded symbols for /home/tomato/Project/Single_mt7688/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib/libcrypto.so.1.0.0
Reading symbols from /home/tomato/Project/Single_mt7688/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib/libcap.so.2.24...(no debugging symbols found)...done.
Loaded symbols for /home/tomato/Project/Single_mt7688/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib/libcap.so.2.24
(gdb) bt
#0  0x76ff33b8 in lws_ssl_capable_read (wsi=0x49d1c0, buf=<optimized out>, len=<optimized out>)
    at /home/tomato/Project/Single_mt7688/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/libwebsockets-openssl/libwebsockets-3.0.1/lib/tls/openssl/ssl.c:300
#1  0x00000000 in ?? ()
(gdb) quit
```

**Comment by lhlonng** [comment]
Hi:
 i disable the option of ipv6, and finally the app works well with new lib.  
 thanks for your reply！

**Comment by lws-team** [comment]
... ok... but it doesn't nail down whatever the problem is.

You found that your server doesn't listen on ipv6, or it does?

**Comment by lhlonng** [comment]
there is no server in the machine， actually，no matter what domain name is specified，the app get segfault。
