### ISSUE TITLE
ESP32's new CMake Build System issue

### ISSUE THREAD

**Issue by huming2207** [warmcat/libwebsockets#1462]
Hi there,

It looks like the current CMakeList for this library is only designed for generic CMake project and it is not working for [ESP32's new build system](https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/build-system-cmake.html#using-third-party-cmake-projects-with-components). There is a new way to force binding the generic CMake project, but it didn't work for me.

Here is the document for binding generic CMake project: https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/build-system-cmake.html#using-third-party-cmake-projects-with-components

Here is what I have written in my main component's CMake list (the `${PROJECT_PATH}/main/CMakeList.txt`):

```cmake
set(COMPONENT_SRCS "hello_world_main.c")
set(COMPONENT_ADD_INCLUDEDIRS "")

register_component()

set(IDF_PATH ${IDF_PATH})
set(BUILD_DIR_BASE ${PROJECT_PATH}/build)
set(CMAKE_TOOLCHAIN_FILE "libwebsockets/contrib/cross-esp32.cmake")
execute_process(COMMAND "dirname `which xtensa-esp32-elf-gcc`" OUTPUT_VARIABLE CROSS_PATH)
set(LWS_MBEDTLS_INCLUDE_DIRS ${IDF_PATH}/components/openssl/include;${IDF_PATH}/components/mbedtls/mbedtls/include;${IDF_PATH}/components/mbedtls/port/include)
set(LWS_WITH_ESP32 1)
set(LWS_WITH_ZLIB 0)
set(LWS_WITH_STATS 0)
set(LWS_WITH_ZIP_FOPS 0)

add_subdirectory("libwebsockets")

target_include_directories(libwebsockets ${IDF_INCLUDE_DIRECTORIES})
target_compile_options(libwebsockets ${IDF_COMPILE_OPTIONS})
target_compile_definitions(libwebsockets ${IDF_COMPILE_DEFINITIONS})

target_link_libraries(main libwebsockets)
```

Here is the error log when I run `idf.py build`:

```
Checking Python dependencies...
Python requirements from /home/jackson/esp/esp-idf/requirements.txt are satisfied.
Running cmake in directory /home/jackson/Projects/WebSocketTest/build
Executing "cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 --warn-uninitialized /home/jackson/Projects/WebSocketTest"...
Warn about uninitialized values.
-- Found Git: /usr/bin/git (found version "2.19.1") 
-- IDF_TARGET not set, using default target: esp32
-- Building for target esp32
-- The C compiler identification is GNU 5.2.0
-- The CXX compiler identification is GNU 5.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /home/jackson/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
-- Check for working C compiler: /home/jackson/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
-- Check for working C compiler: /home/jackson/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/jackson/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++
-- Check for working CXX compiler: /home/jackson/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /home/jackson/Projects/WebSocketTest/main/libwebsockets/CMakeLists.txt:188 (project):
  project command is not scriptable
Call Stack (most recent call first):
  /home/jackson/esp/esp-idf/tools/cmake/scripts/expand_requirements.cmake:105 (include)
  /home/jackson/esp/esp-idf/tools/cmake/scripts/expand_requirements.cmake:112 (expand_component_requirements)
  /home/jackson/esp/esp-idf/tools/cmake/scripts/expand_requirements.cmake:215 (expand_component_requirements)


CMake Error at /home/jackson/esp/esp-idf/CMakeLists.txt:36 (include):
  include could not find load file:

    /home/jackson/Projects/WebSocketTest/build/component_depends.cmake


-- Component names: 
-- Component paths: 
Traceback (most recent call last):
  File "/home/jackson/esp/esp-idf/tools/kconfig_new/confgen.py", line 296, in <module>
    main()
  File "/home/jackson/esp/esp-idf/tools/kconfig_new/confgen.py", line 86, in main
    config = kconfiglib.Kconfig(args.kconfig)
  File "/home/jackson/esp/esp-idf/tools/kconfig_new/kconfiglib.py", line 653, in __init__
    self.top_node)  # prev_node
  File "/home/jackson/esp/esp-idf/tools/kconfig_new/kconfiglib.py", line 1546, in _parse_block
    self._enter_file(sourced_file)
  File "/home/jackson/esp/esp-idf/tools/kconfig_new/kconfiglib.py", line 1130, in _enter_file
    .format(self._filename, self._linenr, e.message))
IOError: /home/jackson/esp/esp-idf/Kconfig:59: Could not open '' (ENOENT: No such file or directory). Perhaps the $srctree environment variable (which was unset) is set incorrectly. Note that the current value of $srctree is saved when the Kconfig instance is created (for consistency and to cleanly separate instances). Also note that e.g. $FOO in a 'source' statement does not refer to the environment variable FOO, but rather to the Kconfig Symbol FOO (which would commonly have 'option env="FOO"' in its definition).
CMake Error at /home/jackson/esp/esp-idf/tools/cmake/kconfig.cmake:153 (message):
  Failed to run confgen.py
  (/usr/bin/python;/home/jackson/esp/esp-idf/tools/kconfig_new/confgen.py;--kconfig;/home/jackson/esp/esp-idf/Kconfig;--config;/home/jackson/Projects/WebSocketTest/sdkconfig;--create-config-if-missing;--env;COMPONENT_KCONFIGS=;--env;COMPONENT_KCONFIGS_PROJBUILD=;--env;IDF_CMAKE=y).
  Error 1
Call Stack (most recent call first):
  /home/jackson/esp/esp-idf/CMakeLists.txt:62 (kconfig_process_config)


-- Configuring incomplete, errors occurred!
See also "/home/jackson/Projects/WebSocketTest/build/CMakeFiles/CMakeOutput.log".
See also "/home/jackson/Projects/WebSocketTest/build/CMakeFiles/CMakeError.log".
cmake failed with exit code 1

```

It's saying `project command is not scriptable` while probably somewhere in the ESP32 build system script, CMake is running in scripting mode with `-P` parameter.

So I would like to know did I write something wrong in my main component's CMakeList? Or is that this project actually hasn't been added support for the ESP32's new build system yet?

Please let me know if there is something I can help to fix this.

Regards,
Jackson

**Comment by perfectsun1990** [comment]
Hi!  try `https://github.com/ASPLes/nopoll.git`, good luck!

**Comment by lws-team** [comment]
I haven't looked at the new ESP stuff yet... at mid-Feb I will either be spending some quality time with RTOS ports like this ongoing, and look at it as part of that, or it'll have to wait until I do get a reason to spend more time on it.  I'll report back what to expect then.

**Comment by huming2207** [comment]
@lws-team Thanks for your reply. I'm also implementing my own WS library.

**Comment by lws-team** [comment]
Then I'll close this...
