### ISSUE TITLE
core is sometimes generated when connecting clients to a server

### ISSUE THREAD

**Issue by Joecpu** [warmcat/libwebsockets#1679]
Hi Lws-team,

I sometimes get a "Program terminated with signal 6, Aborted." when connecting clients to the server. 
Back trace for this is as follows

 [Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./Server --ssl -d65535'.
Program terminated with signal 6, Aborted.
#0  0x00007fb93938b277 in raise () from /usr/lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-222.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-19.el7.x86_64 libcom_err-1.42.9-12.el7_5.x86_64 libgcc-4.8.5-28.el7_5.1.x86_64 libselinux-2.5-14.1.el7.x86_64 libstdc++-4.8.5-28.el7_5.1.x86_64 openssl-libs-1.0.2k-12.el7.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x00007fb93938b277 in raise () from /usr/lib64/libc.so.6
#1  0x00007fb93938c968 in abort () from /usr/lib64/libc.so.6
#2  0x00007fb939384096 in __assert_fail_base () from /usr/lib64/libc.so.6
#3  0x00007fb939384142 in __assert_fail () from /usr/lib64/libc.so.6
#4  0x0000000000442449 in insert_wsi (context=0xa6ec90, wsi=0x7fb8cd9d8c60)
    at /vagrant/libwebsockets-master/lib/plat/unix/unix-fds.c:53
#5  0x0000000000419f07 in __insert_wsi_socket_into_fds (context=0xa6ec90, wsi=0x7fb8cd9d8c60)
    at /vagrant/libwebsockets-master/lib/core-net/pollfd.c:270
#6  0x0000000000432764 in lws_server_socket_service_ssl (wsi=0x7fb8cd9d8c60, accept_fd=4676)
    at /vagrant/libwebsockets-master/lib/tls/tls-server.c:233
#7  0x000000000044ac8a in lws_adopt_descriptor_vhost (vh=0xaea7e0, type=7, fd=..., vh_prot_name=0x0, parent=0x0)
    at /vagrant/libwebsockets-master/lib/core-net/adopt.c:243
#8  0x000000000044b5a1 in rops_handle_POLLIN_listen (pt=0xa6fa10, wsi=0xbb8560, pollfd=0x7fb93aa36ec0)
    at /vagrant/libwebsockets-master/lib/roles/listen/ops-listen.c:138
#9  0x000000000041c9e6 in lws_service_fd_tsi (context=0xa6ec90, pollfd=0x7fb93aa36ec0, tsi=9)
    at /vagrant/libwebsockets-master/lib/core-net/service.c:1050
#10 0x0000000000441d74 in _lws_plat_service_tsi (context=0xa6ec90, timeout_ms=50, tsi=9)
    at /vagrant/libwebsockets-master/lib/plat/unix/unix-service.c:185
#11 0x000000000041cc47 in lws_service_tsi (context=0xa6ec90, timeout_ms=50, tsi=9)
    at /vagrant/libwebsockets-master/lib/core-net/service.c:1147
#12 0x00000000004106f7 in thread_service (threadid=0x9)
    at /vagrant/libwebsockets-master/test-apps/tunnel/tunnel-server.C:1610
#13 0x00007fb939729e25 in start_thread () from /usr/lib64/libpthread.so.0
#14 0x00007fb939453bad in clone () from /usr/lib64/libc.so.6

output of program when terminated:
Server: /vagrant/libwebsockets-master/lib/plat/unix/unix-fds.c:54: insert_wsi: Assertion `context->lws_lookup[wsi->desc.sockfd - (0)] == 0' failed.

Could you please help me.

**Comment by lws-team** [comment]
You don't mention the exact lws version... it says "libwebsockets-master" in the path but it doesn't seem to be today's master.  I guess it's this though

```
int
insert_wsi(const struct lws_context *context, struct lws *wsi)
{
	struct lws **p, **done;

	if (!context->max_fds_unrelated_to_ulimit) {
		assert(context->lws_lookup[wsi->desc.sockfd -
		                           lws_plat_socket_offset()] == 0);
```

lws maintains a central lookup table for fds to wsis... at the time we're planning to make a new entry in there, it should be that it's no in use by anything already.  And it seems it is.

You're using the multi service thread stuff, since for this kind of thing probably lws itself should be responsible for handling the locking, what I would suggest is align to the latest master lws from today, and build and test the minimal-http-server-smp example for your platform instead of your app

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-smp

and see if that shows the same problem (I have exactly the same code then).  There's another wrinkle which is OpenSSL, it only became threadsafe after 1.0.2k, before that it needed special workarounds which I added about 6 weeks ago, just before v3.2

https://libwebsockets.org/git/libwebsockets/commit?id=bd36962c173b539f5899d26a8668057568148c3e

...so the exact version of lws master you have is important for your case... again see what happens with current stuff.
