### ISSUE TITLE
__lws_sul_service_ripe: Assertion `sul->us' failed.

### ISSUE THREAD

**Issue by JCYAO-gz** [warmcat/libwebsockets#2089]
sometimes it will coredump in this case

log:
```
[16:51:27.702] [D] [WsWebsocketsManager.cpp:run2:431] SEND PING
[16:51:27.702] [D] [WsWebsocketsManager.cpp:send:472] wsi=0x69601200,len=10
[2020/10/12 16:51:27:7025] I: lws_issue_raw: ssl_capable_write (28) says 28
[16:51:27.702] [D] [WsWebsocketsManager.cpp:cvt_lws_write:527] send len=22,ret=28,lws_write_protocol=5
[16:51:27.702] [D] [WsWebsocketsManager.cpp:lws_client_callback:12] wsi=0x69601200,reason=10
[16:51:27.702] [D] [WsWebsocketsManager.cpp:getWsContextByWsi:160] m_wsContextList.size()=1
[16:51:27.703] [D] [WsWebsocketsManager.cpp:lws_client_callback:70] LWS_CALLBACK_CLIENT_WRITEABLE
[2020/10/12 16:51:27:7036] I: lws_ws_client_rx_sm: client 0x69601200 received pong
[2020/10/12 16:51:27:7038] I: _lws_validity_confirmed_role: wsi 0x69601200: setting validity timer 300s (hup 0)
[2020/10/12 16:51:27:7039] I: Client doing pong callback
[16:51:27.704] [D] [WsWebsocketsManager.cpp:lws_client_callback:12] wsi=0x69601200,reason=9
[16:51:27.704] [D] [WsWebsocketsManager.cpp:getWsContextByWsi:160] m_wsContextList.size()=1
test_raspberry: /data/tools/libwebsockets_v4.0.19/libwebsockets/lib/core-net/sorted-usec-list.c:123: __lws_sul_service_ripe: Assertion `sul->us' failed.
已放弃 (核心已转储)
```
corddump:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: 没有那个文件或目录.
[Current thread is 1 (Thread 0x6c1ff450 (LWP 3690))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x76bcd824 in __GI_abort () at abort.c:89
#2  0x76bc51a4 in __assert_fail_base (fmt=0x6c1ff450 "\001", assertion=0x462d84 "sul->us",
    assertion@entry=0x2 <error: Cannot access memory at address 0x2>, file=0x6c1fe9fc " ", file@entry=0x76cdd078 <lock> "", line=123,
    line@entry=1814033488, function=function@entry=0x462da0 <__PRETTY_FUNCTION__.33492> "__lws_sul_service_ripe") at assert.c:92
#3  0x76bc5280 in __GI___assert_fail (assertion=0x2 <error: Cannot access memory at address 0x2>, file=0x76cdd078 <lock> "", line=1814033488,
    function=0x462da0 <__PRETTY_FUNCTION__.33492> "__lws_sul_service_ripe") at assert.c:101
#4  0x001fc924 in __lws_sul_service_ripe (own=0x6cc127dc, usnow=1602492691117136)
    at /data/tools/libwebsockets_v4.0.19/libwebsockets/lib/core-net/sorted-usec-list.c:123
#5  0x002155a0 in _lws_plat_service_tsi (context=0x6cc12728, timeout_ms=2000000000, tsi=0)
    at /data/tools/libwebsockets_v4.0.19/libwebsockets/lib/plat/unix/unix-service.c:116
#6  0x00215844 in lws_plat_service (context=0x6cc12728, timeout_ms=0)
    at /data/tools/libwebsockets_v4.0.19/libwebsockets/lib/plat/unix/unix-service.c:221
#7  0x001fc5f4 in lws_service (context=0x6cc12728, timeout_ms=0) at /data/tools/libwebsockets_v4.0.19/libwebsockets/lib/core-net/service.c:770
#8  0x00139800 in cr::WsWebsocketsManager::run() ()

```
Thank you for your help

**Comment by lws-team** [comment]
Problem exists without your code?

Problem exists on master?

Tried running your code under valgrind?

**Comment by JCYAO-gz** [comment]
> Problem exists without your code?
> 
> Problem exists on master?
> 
> Tried running your code under valgrind?

in my project
is master
i will test in valgrind

**Comment by lws-team** [comment]
> Problem exists without your code?

Yeah but with the last bug, the problem was in your code.  If you think things are crashing in lws itself, well, it's possible, but then it should also be possible to show a minimal example crashing.

I am not here to debug your code for you, I am only concerned if something to do with lws itself.

**Comment by JCYAO-gz** [comment]
> > Problem exists without your code?
> 
> Yeah but with the last bug, the problem was in your code. If you think things are crashing in lws itself, well, it's possible, but then it should also be possible to show a minimal example crashing.
> 
> I am not here to debug your code for you, I am only concerned if something to do with lws itself.

yes,i konw!  i just hope get some help from you，maybe it is my code call the lws api error ，i will analysis by myself。
If you can see the reason right away，it is the best.
anyway, i will analysis continue, Thank you very much

**Comment by JCYAO-gz** [comment]
i will handle other work a few days，this problem close temporarily.
Thank you for your support
