### ISSUE TITLE
crash on stress test

### ISSUE THREAD

**Issue by liberize** [warmcat/libwebsockets#2394]
I'm using libwebsockets 4.2.1 with LWS_MAX_SMP=48.
I run some stress test with 300 connections simultaneously.
I noticed some crashes with the following stacktrace, no matter how many service threads started (1 or 2).

```
(gdb) bt
#0  0x00007f35926ab3d7 in raise () from /lib64/libc.so.6
#1  0x00007f35926acac8 in abort () from /lib64/libc.so.6
#2  0x00007f35926a41a6 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007f35926a4252 in __assert_fail () from /lib64/libc.so.6
#4  0x00007f3593e52ac5 in lws_mutex_refcount_assert_held () from libwebsockets.so.18
#5  0x00007f3593e5bfd5 in __lws_free_wsi () from libwebsockets.so.18
#6  0x00007f3593e5d375 in __lws_close_free_wsi_final () from libwebsockets.so.18
#7  0x00007f3593e5d1dd in __lws_close_free_wsi () from libwebsockets.so.18
#8  0x00007f3593e683c3 in lws_validity_cb () from libwebsockets.so.18
#9  0x00007f3593e64702 in __lws_sul_service_ripe () from libwebsockets.so.18
#10 0x00007f3593e4be9a in _lws_plat_service_tsi () from libwebsockets.so.18
#11 0x00007f3593e643ee in lws_service_tsi () from libwebsockets.so.18
#12 0x000000000042c38a in WebSocketServer::Run (this=0x664480 <WebSocketServer& Singleton<WebSocketServer>()::instance>, threadIndex=0)
    at WebSocketServer.cpp:121
#13 0x00007f3593010330 in ?? () from /lib64/libstdc++.so.6
#14 0x00007f359326aea5 in start_thread () from /lib64/libpthread.so.0
#15 0x00007f35927739fd in clone () from /lib64/libc.so.6
```

**Comment by liberize** [comment]
Strange, i can't reproduce the crash...
...Close for now.

**Comment by lws-team** [comment]
That crash is related to closing because a connection was idle and not responding to ping for too long... for SMP mode, it was a real bug, but you won't reproduce it without those conditions failing validity check.
