### ISSUE TITLE
Trac on https://libwebsockets.org/

### ISSUE THREAD

**Issue by fabaff** [warmcat/libwebsockets#246]
The trac instance on https://libwebsockets.org/ gives me: 
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/trac/web/api.py", line 556, in send_error
    data, 'text/html')
  File "/usr/lib/python2.7/site-packages/trac/web/chrome.py", line 1022, in render_template
    if req.form_token:
  File "/usr/lib/python2.7/site-packages/trac/web/api.py", line 353, in __getattr__
    value = self.callbacks[name](self)
  File "/usr/lib/python2.7/site-packages/trac/web/main.py", line 320, in _get_form_token
    req.outcookie['trac_form_token'] = hex_entropy(24)
  File "/usr/lib/python2.7/site-packages/trac/util/__init__.py", line 797, in hex_entropy
    result = ''.join('%.2x' % ord(v) for v in urandom((digits + 1) // 2))
NotImplementedError: /dev/urandom (or equivalent) not found
```

**Comment by warmcat** [comment]
Sorry I restarted httpd thismorning and he's OK.

It's strange since he's been stable for a year (running F20) and the other services have no problems.

**Comment by fabaff** [comment]
Thanks...one rpmlint warning less ;-)
