### ISSUE TITLE
minimal-ws-server crashing

### ISSUE THREAD

**Issue by sackett** [warmcat/libwebsockets#2472]
crashing when open localhost:7681

(gdb) run
Starting program: /home/projects/libwebsockets/minimal-examples-lowlevel/ws-server/minimal-ws-server/lws-minimal-ws-server 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[2021/11/01 09:44:52:4729] U: LWS minimal ws server | visit http://localhost:7681 (-s = use TLS / https)
[2021/11/01 09:44:52:4731] N: localhost: lws_create_context: LWS: 4.3.99-v4.3.0-64-g1440dae7, NET CLI SRV H1 H2 WS MQTT SS-JSON-POL SSPROX ConMon IPV6-on
[2021/11/01 09:44:52:4731] N: localhost: __lws_lc_tag:  ++ [8680|wsi|0|pipe] (1)
[2021/11/01 09:44:52:4732] N: localhost: __lws_lc_tag:  ++ [8680|vh|0|netlink] (1)
[2021/11/01 09:44:52:4733] N: localhost: __lws_lc_tag:  ++ [8680|vh|1|localhost||7681] (2)
[2021/11/01 09:44:52:4733] N: [8680|vh|1|localhost||7681]: lws_socket_bind: source ads 0.0.0.0
[2021/11/01 09:44:52:4733] N: localhost: __lws_lc_tag:  ++ [8680|wsi|1|listen|localhost||7681] (2)
[2021/11/01 09:44:52:4733] N: [8680|vh|1|localhost||7681]: lws_socket_bind: source ads ::
[2021/11/01 09:44:52:4734] N: localhost: __lws_lc_tag:  ++ [8680|wsi|2|listen|localhost||7681] (3)
[2021/11/01 09:44:55:1662] N: localhost: __lws_lc_tag:  ++ [8680|wsisrv|0|localhost|(null)] (1)
[2021/11/01 09:44:55:1676] N: localhost: __lws_lc_tag:  ++ [8680|wsisrv|1|localhost|(null)] (2)
[2021/11/01 09:44:55:2901] N: localhost: __lws_lc_tag:  ++ [8680|wsisrv|2|localhost|(null)] (3)

Program received signal SIGSEGV, Segmentation fault.
0x000055555556443d in callback_minimal (wsi=0x55555567d520, reason=LWS_CALLBACK_ESTABLISHED, user=0x55555564a8c0, in=0x0, len=0)
    at /home/projects/libwebsockets/minimal-examples-lowlevel/ws-server/minimal-ws-server/protocol_lws_minimal.c:86
86                      lws_ll_fwd_insert(pss, pss_list, vhd->pss_list);
(gdb) bt
#0  0x000055555556443d in callback_minimal (wsi=0x55555567d520, reason=LWS_CALLBACK_ESTABLISHED, user=0x55555564a8c0, in=0x0, len=0)
    at /home/projects/libwebsockets/minimal-examples-lowlevel/ws-server/minimal-ws-server/protocol_lws_minimal.c:86
#1  0x00005555555b6594 in lws_server_init_wsi_for_ws ()
#2  0x00005555555bd78c in lws_process_ws_upgrade2 ()
#3  0x00005555555bdf09 in lws_process_ws_upgrade ()
#4  0x00005555555a0601 in lws_handshake_server ()
#5  0x00005555555a5c03 in lws_read_h1 ()
#6  0x00005555555a66f0 in lws_h1_server_socket_service ()
#7  0x00005555555a6ce8 in rops_handle_POLLIN_h1 ()
#8  0x0000555555584bc6 in lws_service_fd_tsi ()
#9  0x00005555555e7214 in _lws_plat_service_forced_tsi ()
#10 0x00005555555e765f in _lws_plat_service_tsi ()
#11 0x00005555555e76f4 in lws_plat_service ()
#12 0x0000555555584dde in lws_service ()
#13 0x0000555555564883 in main (argc=1, argv=0x7fffffffddd8) at /home/projects/libwebsockets/minimal-examples-lowlevel/ws-server/minimal-ws-server/minimal-ws-server.c:113

**Comment by lws-team** [comment]
Can't reproduce it here on current main (also seems to be what you're using) on Fedora 35

```
[2021/11/01 07:48:17:9710] U: LWS minimal ws server | visit http://localhost:7681 (-s = use TLS / https)
[2021/11/01 07:48:17:9711] N: localhost: lws_create_context: LWS: 4.3.99-v4.3.0-64-g1440dae7cd, NET CLI SRV H1 H2 WS MQTT SS-JSON-POL SSPROX ConMon ASYNC_DNS IPV6-on
[2021/11/01 07:48:17:9712] N: localhost: __lws_lc_tag:  ++ [1783273|wsi|0|pipe] (1)
[2021/11/01 07:48:17:9713] N: localhost: __lws_lc_tag:  ++ [1783273|vh|0|netlink] (1)
[2021/11/01 07:48:17:9713] N: localhost: __lws_lc_tag:  ++ [1783273|vh|1|system||-1] (2)
[2021/11/01 07:48:17:9716] N: localhost: __lws_lc_tag:  ++ [1783273|wsisrv|0|system|asyncdns] (1)
[2021/11/01 07:48:17:9721] N: localhost: __lws_lc_tag:  ++ [1783273|vh|2|localhost||7681] (3)
[2021/11/01 07:48:17:9722] N: [1783273|vh|2|localhost||7681]: lws_socket_bind: source ads 0.0.0.0
[2021/11/01 07:48:17:9723] N: localhost: __lws_lc_tag:  ++ [1783273|wsi|1|listen|localhost||7681] (2)
[2021/11/01 07:48:17:9723] N: [1783273|vh|2|localhost||7681]: lws_socket_bind: source ads ::
[2021/11/01 07:48:17:9723] N: localhost: __lws_lc_tag:  ++ [1783273|wsi|2|listen|localhost||7681] (3)
[2021/11/01 07:48:28:5193] N: localhost: __lws_lc_tag:  ++ [1783273|wsisrv|1|localhost|(null)] (2)
[2021/11/01 07:48:28:5541] N: localhost: __lws_lc_tag:  ++ [1783273|wsisrv|2|localhost|(null)] (3)
[2021/11/01 07:48:28:5759] N: localhost: __lws_lc_tag:  ++ [1783273|wsisrv|3|localhost|(null)] (4)
[2021/11/01 07:48:33:5580] N: localhost: __lws_lc_untag:  -- [1783273|wsisrv|1|localhost|(null)] (3) 5.038s
[2021/11/01 07:48:33:5816] N: localhost: __lws_lc_untag:  -- [1783273|wsisrv|2|localhost|(null)] (2) 5.027s
```

what's your platform?

**Comment by sackett** [comment]
5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
got lws with git clone https://github.com/warmcat/libwebsockets.git
compiled with -DLWS_WITH_DISTRO_RECOMMENDED=1

ldd lws-minimal-ws-server (why no libwebsockets.so ?)
        linux-vdso.so.1 (0x00007ffde5e38000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f10098cd000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f10098aa000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f100988e000)
        libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f10097fb000)
        libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f1009525000)
        libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f10094d4000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f10092e0000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f10099e0000)
        libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f1009231000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f1009226000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f10091fd000)
        liblz4.so.1 => /lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f10091dc000)
        libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f10090be000)
        libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f1009099000)

**Comment by lws-team** [comment]
> compiled with -DLWS_WITH_DISTRO_RECOMMENDED=1

I can reproduce it on Fedora with that... taking a look...

**Comment by lws-team** [comment]
It's coming because DISTRO_RECOMMENDED enables LWS_WITH_PLUGINS via enabling LWS_WITH_LWSWS.

That's OK, but it changes the rules for enabling protocols on vhosts... if you are using lwsws and protocol plugins, you won't want every available protocol enabled on to every vhost.  So it requires a pvo (per-vhost option) on the vhost naming the protocols it wants enabled on it.  In lwsws JSON, it looks like


```
     ...
        {
                "name": "warmcat.com",
                "port": "443",
...
                "ws-protocols": [{
                        "lws-deaddrop": {
                         "status": "ok",
                         ...
```

to indicate that you want deaddrop enable on warmcat.com.

For simplicity and backwards compatibility, if you are not using plugins, then any protocols you give are assumed to be wanted on all vhosts.

The crash is coming because the INIT_PROTOCOL that sets up the vhd, was not called at protocol init time because of the above.

You can solve it by giving the pvo at vhost creation time listing the protocols you want to bind to the vhost

```
diff --git a/minimal-examples-lowlevel/ws-server/minimal-ws-server/minimal-ws-server.c b/minimal-examples-lowlevel/ws-server/minimal-ws-server/minimal-ws-server.c
index 921bcffaf2..7855aa3a9c 100644
--- a/minimal-examples-lowlevel/ws-server/minimal-ws-server/minimal-ws-server.c
+++ b/minimal-examples-lowlevel/ws-server/minimal-ws-server/minimal-ws-server.c
@@ -54,6 +54,13 @@ static const struct lws_http_mount mount = {
        /* .basic_auth_login_file */    NULL,
 };
 
+static struct lws_protocol_vhost_options pvo = {
+        NULL,                  /* "next" pvo linked-list */
+        NULL,                 /* "child" pvo linked-list */
+        "lws-minimal",        /* enable the "plugin" protocol for default vhost */
+        ""                     /* ignored */
+};
+
 void sigint_handler(int sig)
 {
        interrupted = 1;
@@ -85,6 +92,7 @@ int main(int argc, const char **argv)
        info.mounts = &mount;
        info.protocols = protocols;
        info.vhost_name = "localhost";
+       info.pvo = &pvo;
        info.options =
                LWS_SERVER_OPTION_HTTP_HEADERS_SECURITY_BEST_PRACTICES_ENFORCE;
 
```

I'll have a think about what to do for the best generally with that.

**Comment by sackett** [comment]
thank you.

**Comment by lws-team** [comment]
I pushed ths patch with an additional comment for now.
