### ISSUE TITLE
sshd Segmentation

### ISSUE THREAD

**Issue by calvin2021y** [warmcat/libwebsockets#2480]
```sh
[2021/11/04 21:15:30:7906] I: [vh|0|system||-1]: lws_protocol_init_vhost: init system.lws-async-dns
[2021/11/04 21:15:30:7906] I: lws_create_context:  mem: per-conn:         1232 bytes + protocol rx buf
[2021/11/04 21:15:30:7906] D: lws_cancel_service: 
[2021/11/04 21:15:30:7906] D: _realloc: size 629: lws_create_vhost
[2021/11/04 21:15:30:7906] N: __lws_lc_tag:  ++ [vh|1|sshd||2200] (2)
[2021/11/04 21:15:30:7906] I: [vh|1|sshd||2200]: lws_create_vhost: set to only support RAW
[2021/11/04 21:15:30:7906] D: _realloc: size 168: vh plugin table
[2021/11/04 21:15:30:7906] D: _realloc: size 48: same vh list
[2021/11/04 21:15:30:7906] I: [vh|1|sshd||2200]: lws_create_vhost: Creating Vhost 'sshd' port 2200, 2 protocols, IPv6 off
[2021/11/04 21:15:30:7906] I: _lws_vhost_init_server_af: af 2
[2021/11/04 21:15:30:7907] N: [vh|1|sshd||2200]: lws_socket_bind: source ads 0.0.0.0
[2021/11/04 21:15:30:7907] D: _realloc: size 1232: __lws_wsi_create_with_role
[2021/11/04 21:15:30:7907] D: : lws_role_transition: wsistate 0x200, ops listen
[2021/11/04 21:15:30:7907] D: _lws_vhost_init_server_af: lws_socket_bind says 2200
[2021/11/04 21:15:30:7907] D: : lws_vhost_bind_wsi: vh sshd: wsi listen/lws-sshd-demo, count_bound_wsi 1
[2021/11/04 21:15:30:7907] D: : __insert_wsi_socket_into_fds: tsi=0, sock=6, pos-in-fds=2
[2021/11/04 21:15:30:7907] N: __lws_lc_tag:  ++ [wsi|1|listen|sshd||2200] (2)
[2021/11/04 21:15:30:7907] I: lws_protocol_init: 
[2021/11/04 21:15:30:7907] D: [vh|1|sshd||2200]: lws_protocol_init_vhost: not instantiating lws-sshd-demo
[2021/11/04 21:15:30:7907] I: lws_plat_drop_app_privileges: not changing group
[2021/11/04 21:15:30:7907] I: lws_plat_drop_app_privileges: not changing user

Program received signal SIGSEGV, Segmentation fault.
0x00000000005774b0 in pvo_ssh_ops ()
(gdb) bt
#0  0x00000000005774b0 in pvo_ssh_ops ()
#1  0x00000000002e1f5b in lws_broadcast (pt=0x59ec48, reason=71, in=0x0, len=0) at lib/core-net/wsi.c:869
#2  0x00000000005730d4 in rops_handle_POLLIN_pipe (pt=0x59ec48, wsi=0x5a46a0, pollfd=0x5a0680) at lib/roles/pipe/ops-pipe.c:111
#3  0x0000000000512282 in lws_service_fd_tsi (context=0x59ea50, pollfd=0x5a0680, tsi=0) at lib/core-net/service.c:762
#4  0x000000000051370b in _lws_plat_service_forced_tsi (context=0x59ea50, tsi=0) at lib/plat/unix/unix-service.c:51
#5  0x0000000000513b35 in _lws_plat_service_tsi (context=0x59ea50, timeout_ms=2000000000, tsi=0) at lib/plat/unix/unix-service.c:216
#6  0x0000000000513bbd in lws_plat_service (context=0x59ea50, timeout_ms=0) at lib/plat/unix/unix-service.c:235
#7  0x00000000005124b2 in lws_service (context=0x59ea50, timeout_ms=0) at lib/core-net/service.c:834
```

**Comment by lws-team** [comment]
I pushed some patches on main to bring that example up-to-date in various ways, pleas give it a try.

**Comment by calvin2021y** [comment]
after update:
```sh
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[2021/11/08 21:51:19:0753] N: lws test-sshd -- Copyright (C) 2017 <andy@warmcat.com>
[2021/11/08 21:51:19:0754] N: lws_create_context: LWS: 4.3.99-root@z77-v4.3.0-67-g5ec003ec, NET CLI SRV H1 H2 WS ConMon ASYNC_DNS IPv6-absent
[2021/11/08 21:51:19:0754] N: __lws_lc_tag:  ++ [wsi|0|pipe] (1)
[2021/11/08 21:51:19:0756] N: __lws_lc_tag:  ++ [vh|0|system||-1] (1)
[2021/11/08 21:51:19:0756] N: __lws_lc_tag:  ++ [wsisrv|0|system|asyncdns] (1)
[2021/11/08 21:51:19:0756] N: __lws_lc_tag:  ++ [vh|1|sshd||2200] (2)
[2021/11/08 21:51:19:0757] N: [vh|1|sshd||2200]: lws_socket_bind: source ads 0.0.0.0
[2021/11/08 21:51:19:0757] N: __lws_lc_tag:  ++ [wsi|1|listen|sshd||2200] (2)

Program received signal SIGSEGV, Segmentation fault.
0x00000000005774b0 in pvo_ssh_ops ()
(gdb) bt
#0  0x00000000005774b0 in pvo_ssh_ops ()
#1  0x00000000002e1f5b in lws_broadcast (pt=0x59ec48, reason=71, in=0x0, len=0) at lws/lib/core-net/wsi.c:869
#2  0x00000000005730d4 in rops_handle_POLLIN_pipe (pt=0x59ec48, wsi=0x5a46a0, pollfd=0x5a0680) at  lws/lib/roles/pipe/ops-pipe.c:111
#3  0x0000000000512282 in lws_service_fd_tsi (context=0x59ea50, pollfd=0x5a0680, tsi=0) at lws/lib/core-net/service.c:762
#4  0x000000000051370b in _lws_plat_service_forced_tsi (context=0x59ea50, tsi=0) at lws/lib/plat/unix/unix-service.c:51
#5  0x0000000000513b35 in _lws_plat_service_tsi (context=0x59ea50, timeout_ms=2000000000, tsi=0) at lws/lib/plat/unix/unix-service.c:216
#6  0x0000000000513bbd in lws_plat_service (context=0x59ea50, timeout_ms=0) at ws/lib/plat/unix/unix-service.c:235
#7  0x00000000005124b2 in lws_service (context=0x59ea50, timeout_ms=0) at lws/lib/core-net/service.c:834
#8  0x00000000002d0573 in main () at lws/test-apps/test-sshd.c:777
```

**Comment by lws-team** [comment]
Hm... the patched version says this now

> lwsl_notice("lws test-sshd -- Copyright (C) 2017-2021 <andy@warmcat.com>\n");

**Comment by lws-team** [comment]
... to be clear, it means you're not actually testing the new lws-test-sshd but still the old one.

**Comment by lws-team** [comment]
If main still has problems after the patches, let me know.

**Comment by calvin2021y** [comment]
Thanks for the update, I find the repo from https://libwebsockets.org/repo/libwebsockets and now it work.

There is some error like:

```sh
[2021/11/20 19:35:55:8328] E: [vh|1|sshd||2200]: lws_protocol_vh_priv_get: unknown protocol 0xa27520
[2021/11/20 19:35:55:8328] E: [vh|1|sshd||2200]: lws_protocol_vh_priv_get: unknown protocol 0xa27520
[2021/11/20 19:35:55:8328] N: __lws_lc_untag:  -- [wsi|4|nspawn-stdwsi-2] (4) 1.738min
[2021/11/20 19:35:55:8328] E: [vh|1|sshd||2200]: lws_protocol_vh_priv_get: unknown protocol 0xa27520
[2021/11/20 19:35:55:8328] E: [vh|1|sshd||2200]: lws_protocol_vh_priv_get: unknown protocol 0xa27520
[2021/11/20 19:35:55:8328] N: __lws_lc_untag:  -- [wsi|3|nspawn-stdwsi-1] (3) 1.738min
[2021/11/20 19:35:55:8328] E: [vh|1|sshd||2200]: lws_protocol_vh_priv_get: unknown protocol 0xa27520
[2021/11/20 19:35:55:8328] E: [vh|1|sshd||2200]: lws_protocol_vh_priv_get: unknown protocol 0xa27520

```

If I run top from the shell:
```sh
top
top: failed tty get
```
after some time the terminal is  freezied and not able to do any thing about it.

**Comment by calvin2021y** [comment]
If login 2 shell then sshd stoped:

```sh

[2021/11/20 19:48:02:0489] N: lws test-sshd -- Copyright (C) 2017-2021 <andy@warmcat.com>
[2021/11/20 19:48:02:0490] N: lws_create_context: LWS: 4.3.99-root@z77-v4.3.0-100-ga41040c1, NET CLI SRV H1 H2 WS ConMon ASYNC_DNS IPv6-absent
[2021/11/20 19:48:02:0490] N: __lws_lc_tag:  ++ [wsi|0|pipe] (1)
[2021/11/20 19:48:02:0494] N: __lws_lc_tag:  ++ [vh|0|system||-1] (1)
[2021/11/20 19:48:02:0495] N: __lws_lc_tag:  ++ [wsisrv|0|system|asyncdns] (1)
[2021/11/20 19:48:02:0496] N: __lws_lc_tag:  ++ [wsisrv|1|system|asyncdns] (2)
[2021/11/20 19:48:02:0496] N: __lws_lc_tag:  ++ [vh|1|sshd||2200] (2)
[2021/11/20 19:48:02:0496] N: [vh|1|sshd||2200]: lws_socket_bind: source ads 0.0.0.0
[2021/11/20 19:48:02:0496] N: __lws_lc_tag:  ++ [wsi|1|listen|sshd||2200] (2)
[2021/11/20 19:48:05:0490] N: __lws_lc_tag:  ++ [wsisrv|2|sshd|(null)] (3)
[2021/11/20 19:48:05:0715] N: ssh_ops_pty_req: pty term xterm-256color, modes_len 261
[2021/11/20 19:48:05:0715] N: ssh_cgi_env_add: ENV TERM <- xterm-256color
[2021/11/20 19:48:05:0715] N:  SSHMO_ICRNL: 1
[2021/11/20 19:48:05:0715] N:  SSHMO_ECHO: 1
[2021/11/20 19:48:05:0715] N:  SSHMO_ONLCR: 1
[2021/11/20 19:48:05:0715] N: ssh_cgi_env_add: ENV LANG <- en_US.UTF-8
[2021/11/20 19:48:05:0715] N: ssh_cgi_env_add: ENV LC_ALL <- en_US.UTF-8
[2021/11/20 19:48:05:0715] N: ssh_ops_shell: SHELL
[2021/11/20 19:48:05:0715] N: __lws_lc_tag:  ++ [wsi|2|nspawn-stdwsi-0] (3)
[2021/11/20 19:48:05:0715] N: __lws_lc_tag:  ++ [wsi|3|nspawn-stdwsi-1] (4)
[2021/11/20 19:48:05:0715] N: __lws_lc_tag:  ++ [wsi|4|nspawn-stdwsi-2] (5)
[2021/11/20 19:48:05:0716] N: associated PID 194094 to ch 0
[2021/11/20 19:48:05:0716] N: STDIN
[2021/11/20 19:48:12:8347] N: __lws_lc_tag:  ++ [wsisrv|3|sshd|(null)] (4)
[2021/11/20 19:48:12:8569] N: ssh_ops_pty_req: pty term xterm-256color, modes_len 261
[2021/11/20 19:48:12:8569] N: ssh_cgi_env_add: ENV TERM <- xterm-256color
[2021/11/20 19:48:12:8569] N:  SSHMO_ICRNL: 1
[2021/11/20 19:48:12:8569] N:  SSHMO_ECHO: 1
[2021/11/20 19:48:12:8569] N:  SSHMO_ONLCR: 1
[2021/11/20 19:48:12:8569] N: ssh_cgi_env_add: ENV LANG <- en_US.UTF-8
[2021/11/20 19:48:12:8569] N: ssh_cgi_env_add: ENV LC_ALL <- en_US.UTF-8
[2021/11/20 19:48:12:8569] N: ssh_ops_shell: SHELL
[2021/11/20 19:48:12:8570] N: __lws_lc_tag:  ++ [wsi|5|nspawn-stdwsi-0] (6)
[2021/11/20 19:48:12:8570] N: __lws_lc_tag:  ++ [wsi|6|nspawn-stdwsi-1] (7)
[2021/11/20 19:48:12:8570] N: __lws_lc_tag:  ++ [wsi|7|nspawn-stdwsi-2] (8)
[2021/11/20 19:48:12:8571] N: associated PID 194135 to ch 0
[2021/11/20 19:48:12:8571] N: STDIN

[1]+  Stopped                 ./sshd

```

**Comment by calvin2021y** [comment]
@lws-team

**Comment by lws-team** [comment]
I looked at this over the weekend, you can run top -b to not need the tty.

The "stopped" thing is also to do with which process is bound to the original tty the server was started in, the second bash process is put in the background but the original one and the server continue working owning the original tty.  There's a similar problem with ^C processing, the subprocess sees the ^C in the server tty not the client one.  These are limitations with the terminal demo, not the ssh stuff underneath, you're welcome to extend the demo if you care about it.

I couldn't reproduce the terminal "freezing".

The interesting bit for lws is the sshd protocol, I don't think it will be commonly used to provide a shell but for other purposes.

**Comment by calvin2021y** [comment]
Thanks for explain.
