### ISSUE TITLE
SEGV BugReport, Fuzzing suggestion

### ISSUE THREAD

**Issue by autofuzzoss** [warmcat/libwebsockets#2687]
# System information (version)
- Commit: 96a548ca96a1f06f2ef526c4fb8e4f3eb7c578d2
- Operating System / Platform : ubuntu 18.04
- Compiler : clang++ 10.0.1

# Reproduce code
```cpp
#include "libwebsockets.h"

const uint8_t buginput[] =
    { 0x1f, 0x8b, 0x08, 0x00 ,0x00, 0x00, 0x10, 0x00, 0x00, 0x72, 0x72, 0x72,
      0x72, 0x72, 0x72, 0x52, 0x72, 0x72, 0x72, 0x72, 0x72, 0x72, 0x72, 0x72,
      0x72, 0x72, 0x72, 0x72, 0x72, 0x72, 0x72, 0x72, 0x72, 0x72, 0x72, 0x72,
      0x72, 0x72, 0x72, 0x26, 0x00, 0x37, 0x72, 0x72, 0x72, 0x72, 0x72, 0x00,
      0x8b, 0x00, 0x00, 0x1f, 0x8b, 0x08, 0x1f, 0x8b, 0xfd, 0x20, 0x72, 0x72,
      0x72, 0x72, 0x26, 0x00, 0x37, 0x00, 0x00, 0x00, 0x00, 0x72, 0x72, 0x72,
      0x26, 0x00, 0x38, 0x00, 0x26, 0x00, 0x37, 0x00, 0x00, 0x72 };

int main(int argc, char *argv[]) {
  int result = 0;
  struct inflator_ctx *gunz = nullptr;
  const uint8_t *outring;
  size_t outringlen, *opl, *cl = 0;

  gunz = lws_upng_inflator_create(&outring, &outringlen, &opl, &cl);
  if (!gunz) goto bail;

  lws_upng_inflate_data(gunz, buginput, sizeof(buginput) / sizeof(buginput[0]));

bail:
  if (gunz) lws_upng_inflator_destroy(&gunz);
  return 0;
}
```

# Build steps
```bash
mkdir -p build && cd build
cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_AR=/bin/llvm-ar -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_C_FLAGS=-g -DCMAKE_CXX_FLAGS=-g -DCMAKE_EXE_LINKER_FLAGS=-g -DCMAKE_SHARED_LINKER_FLAGS=-g ..
cd build && make -j8
```

# Reason
```cpp
// private-lib-care.h:852
/*the distance codes have their own symbols, 30 used, 2 unused */
#define NUM_DISTANCE_SYMBOLS		32

// private-lib-care.h:926
typedef struct inflator_ctx {
  // ... SKIP
	unsigned int		bitlenD[NUM_DISTANCE_SYMBOLS]; // bitlenD[32]
  // ... SKIP
	unsigned int		hlit;
  // ... SKIP
	unsigned int		i;
  // ... SKIP
} inflator_ctx_t;

// upng-gzip.c:299
static lws_stateful_ret_t
huffman_decode_symbol(inflator_ctx_t *inf, const htree_t *ct, unsigned int *uct)
{
// ... SKIP
		case UPNS_ID_BL_GB_BTYPE_2_16: /* repeat previous */
			r = read_bits(inf, 2, &tu);
			if (r)
				return r;
			count = tu + 3;

			if ((inf->i - 1) < inf->hlit) // false, inf->i is 'unsigned int' type. inf->i - 1 = 4294967295
				val = inf->bitlen[inf->i - 1];
			else
				val = inf->bitlenD[inf->i - inf->hlit - 1]; // Crashed, inf->i : 0, inf->hlit : 272
```

# Address Sanitizer Report
```bash
AddressSanitizer:DEADLYSIGNAL
=================================================================
==62==ERROR: AddressSanitizer: SEGV on unknown address 0x61f400000108 (pc 0x0000004cd582 bp 0x7ffde4904210 sp 0x7ffde4903100 T0)
==62==The signal is caused by a READ memory access.
    #0 0x4cd582 in _lws_upng_inflate_data /root/fuzz-test-generation/exp/libwebsockets/lib/misc/upng-gzip.c:592:11
    #1 0x4d5930 in lws_upng_inflate_data /root/fuzz-test-generation/exp/libwebsockets/lib/misc/upng-gzip.c:1004:6
    #2 0x4c971d in main /root/fuzz-test-generation/exp/libwebsockets/fuzzing/poc1.cpp:21:3
    #3 0x7fe86233cbf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)
    #4 0x41ed39 in _start (/root/fuzz-test-generation/exp_musang/libwebsockets/fuzzing/crash_1/poc1+0x41ed39)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /root/fuzz-test-generation/exp/libwebsockets/lib/misc/upng-gzip.c:592:11 in _lws_upng_inflate_data
==62==ABORTING
```

# Effect

# Recommendations
2 suggestions for security improvements.
[1] Request CVE number for this bug to inform users to prevent potential security vulnerabilities.
[2] Register below fuzzer code to [ossfuzz](https://github.com/google/oss-fuzz) for continuous fuzzing.

## FuzzerCode:
```cpp
#include "libwebsockets.h"

static void lws_api_test_gunzip(FuzzedDataProvider &provider) {
  int result = 0;
  struct inflator_ctx *gunz = nullptr;
  const uint8_t *outring;
  size_t outringlen, *opl, *cl = 0;
  auto input1 = provider.ConsumeRandomLengthString();

  gunz = lws_upng_inflator_create(&outring, &outringlen, &opl, &cl);
  if (!gunz) goto bail;

  lws_upng_inflate_data(gunz, input1.c_str(), input1.size());

bail:
  if (gunz) lws_upng_inflator_destroy(&gunz);
}

extern "C" int LLVMFuzzerTestOneInput(const uint8_t *data, uint32_t size) {
  FuzzedDataProvider provider(data, size);
  auto select = provider.ConsumeIntegralInRange<unsigned char>(0, 1);
  switch (select) {
    case 0:
      lws_api_test_gunzip(provider);
      break;
  }

  return 0;
}
```

**Comment by lws-team** [comment]
> [1] Request CVE number for this bug to inform users to prevent potential security vulnerabilities.
> [2] Register below fuzzer code to [ossfuzz](https://github.com/google/oss-fuzz) for continuous fuzzing.

Thanks for the report and finding the bug. This only exists on main branch and not any release; it's only used for PNG decode and for firmware update blob decompress both of which will be new for the next release v4.4.

I think it might be time to look at CVEs generally but AFAIK they are not reported on development versions?  It's still very good to hear your detailed report so it can be fixed before it is released: thanks a lot.

https://libwebsockets.org/git/libwebsockets/commit?id=6fb072d5c9da12e9e558897a5294bce64b545577

**Comment by autofuzzoss** [comment]
@lws-team 

Thank you for fix the bug.

Additionally, how about add the project to [oss-fuzz](https://github.com/google/oss-fuzz) for continuous fuzzing with fuzzer which I attached in https://github.com/warmcat/libwebsockets/issues/2687#issue-1293820248.
  - For add new project OSS-Fuzz : https://google.github.io/oss-fuzz/getting-started/accepting-new-projects/

Or, can I contribute to this repository by Pull Request to contain the fuzzer?

**Comment by lws-team** [comment]
I opened a PR to add lws to oss-fuzz, thanks for the pointers.

If you'd like to open a PR on lws to add your fuzzing pieces in lws, I think that makes the most sense since it's your work.

**Comment by autofuzzoss** [comment]
@lws-team 
I uploaded PR in https://github.com/google/oss-fuzz/pull/7977
with `build.sh` and `Dockerfile`.

**Comment by lws-team** [comment]
Thanks a lot
