### ISSUE TITLE
Libwebsockets 4.3.1 periodic seg fault

### ISSUE THREAD

**Issue by jeffreytai** [warmcat/libwebsockets#2692]
I've upgraded from libwebsockets 4.1 to 4.3.1 in a project that streams prices 24/7, and now it crashes about once a day when servicing the context, e.g. `lws_service(m_context, 0);`

OpenSSL version: 3.0.3

Source of seg fault where wsi->ws seems to be corrupted:
```
#0  0x00007fe3a90c82e2 in lws_ws_client_rx_sm (c=<optimized out>, wsi=0x7fe38805dab0) at /usr/src/debug/libwebsockets-4.3.1-1.fc36.x86_64/lib/roles/ws/client-parser-ws.c:650
650                             wsi->ws->first_fragment = 0;

(gdb) p wsi
$1 = (struct lws *) 0x7fe38805dab0
(gdb) p wsi->ws
$2 = (struct _lws_websocket_related *) 0x421
(gdb) p *(wsi->ws)
Cannot access memory at address 0x421
```

Backtrace
```
#0  0x00007fe3a90c82e2 in lws_ws_client_rx_sm (c=<optimized out>, wsi=0x7fe38805dab0) at /usr/src/debug/libwebsockets-4.3.1-1.fc36.x86_64/lib/roles/ws/client-parser-ws.c:650
#1  lws_ws_handshake_client (wsi=0x7fe38805dab0, buf=<optimized out>, len=2843) at /usr/src/debug/libwebsockets-4.3.1-1.fc36.x86_64/lib/roles/ws/client-ws.c:132
#2  0x00007fe3a90bc2b5 in lws_read_h1 (wsi=0x7fe38805dab0, buf=<optimized out>, len=4096) at /usr/src/debug/libwebsockets-4.3.1-1.fc36.x86_64/lib/roles/h1/ops-h1.c:262
#3  0x00007fe3a90c745e in rops_handle_POLLIN_ws (pt=0x2a59970, wsi=0x7fe38805dab0, pollfd=0x2a28e28) at /usr/src/debug/libwebsockets-4.3.1-1.fc36.x86_64/lib/roles/ws/ops-ws.c:1183
#4  0x00007fe3a90ac152 in lws_service_fd_tsi (tsi=0, pollfd=0x2a28e28, context=0x2a59690) at /usr/src/debug/libwebsockets-4.3.1-1.fc36.x86_64/lib/core-net/service.c:766
#5  lws_service_fd_tsi (context=0x2a59690, pollfd=0x2a28e28, tsi=0) at /usr/src/debug/libwebsockets-4.3.1-1.fc36.x86_64/lib/core-net/service.c:638
#6  0x00007fe3a90891b2 in _lws_plat_service_forced_tsi (context=context@entry=0x2a59690, tsi=tsi@entry=0) at /usr/src/debug/libwebsockets-4.3.1-1.fc36.x86_64/lib/plat/unix/unix-service.c:51
#7  0x00007fe3a908ecc9 in _lws_plat_service_tsi (context=0x2a59690, timeout_ms=<optimized out>, tsi=0) at /usr/src/debug/libwebsockets-4.3.1-1.fc36.x86_64/lib/plat/unix/unix-service.c:216
#8  0x00007fe3a90abac7 in lws_plat_service (timeout_ms=<optimized out>, context=0x2a59690) at /usr/src/debug/libwebsockets-4.3.1-1.fc36.x86_64/lib/plat/unix/unix-service.c:235
#9  lws_service (timeout_ms=<optimized out>, context=0x2a59690) at /usr/src/debug/libwebsockets-4.3.1-1.fc36.x86_64/lib/core-net/service.c:838
#10 lws_service (context=0x2a59690, timeout_ms=<optimized out>) at /usr/src/debug/libwebsockets-4.3.1-1.fc36.x86_64/lib/core-net/service.c:819
```

If there's any other information that would be useful for debugging, please let me know.

**Comment by lws-team** [comment]
I would run your app under valgrind.  And use v4.3-stable, which is many patches ahead of v4.3.1.

**Comment by lws-team** [comment]
Is there something I can do about this?  If not then I should close it.

**Comment by jeffreytai** [comment]
> Is there something I can do about this?  If not then I should close it.

Thanks just closed it. Still have yet to run under 4.3 stable, appreciate the follow up
