### ISSUE TITLE
lws_client_connect_via_info crashed with no information?

### ISSUE THREAD

**Issue by nealworking** [warmcat/libwebsockets#2769]
I am using libwebsockets to subscribe data from some data supplier.

the normal steps are:
1. connect with the websocket server address.
2. send subscribe request
3. get feedback

in my situation, i need to build a lot of connection by lws_client_connect_via_info. (maybe 20 connections)
and i will bind these connection with one lws_context, and lws_service to get feedback.

if i build less connection, it worked well.
but when i add it to 20, it crashed.

the crashed info is :
```
(gdb) where
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f4262de97f1 in __GI_abort () at abort.c:79
#2  0x00007f4262e32837 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f4262f5fa7b "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007f4262e398ba in malloc_printerr (str=str@entry=0x7f4262f5dba8 "corrupted double-linked list") at malloc.c:5342
#4  0x00007f4262e3e119 in _int_malloc (av=av@entry=0x7f4263194c40 <main_arena>, bytes=bytes@entry=64) at malloc.c:3936
#5  0x00007f4262e402ad in __GI___libc_malloc (bytes=bytes@entry=64) at malloc.c:3075
#6  0x00007f4262eae3f5 in gaih_inet (name=name@entry=0x55831ec5d370 "wsaws.okx.com", service=<optimized out>, req=req@entry=0x7ffc29284010, pai=0x55831eb44568, pai@entry=0x7ffc29283b18, naddrs=naddrs@entry=0x7ffc29283b14, 
    tmpbuf=tmpbuf@entry=0x7ffc29283b80) at ../sysdeps/posix/getaddrinfo.c:1100
#7  0x00007f4262eb0c84 in __GI_getaddrinfo (name=<optimized out>, service=<optimized out>, hints=0x7ffc29284010, pai=0x7ffc29284080) at ../sysdeps/posix/getaddrinfo.c:2300
#8  0x00007f4263412892 in lws_getaddrinfo46 () from /usr/local/lib/libwebsockets.so.19
#9  0x00007f4263412f5a in lws_client_connect_2_dnsreq () from /usr/local/lib/libwebsockets.so.19
#10 0x00007f426341156b in lws_http_client_connect_via_info2 () from /usr/local/lib/libwebsockets.so.19
#11 0x00007f4263417cff in lws_header_table_attach () from /usr/local/lib/libwebsockets.so.19
#12 0x00007f4263428eb9 in rops_client_bind_h1 () from /usr/local/lib/libwebsockets.so.19
#13 0x00007f426341242e in lws_client_connect_via_info () from /usr/local/lib/libwebsockets.so.19
#14 0x000055831d217584 in main (argc=<optimized out>, argv=0x7ffc292849c8) at /home/neal/crypto_data/bin_src/crypto_data/main.cpp:131
```

i had checked many times about my code, and the 5 connections works well indicates it may not code problem.

could you help on this? is there any setting i should know?

how to get error message if lws_client_connect_via_info failed?

**Comment by lws-team** [comment]
There's nothing here indicating it's an lws problem.  Something trashed heap earlier, and this is your code as well as lws.

Use valgrind or similar to find out where things went off the rails.
