### ISSUE TITLE
lws-minimal-ws-broker (Segmentation fault.)

### ISSUE THREAD

**Issue by sackett** [warmcat/libwebsockets#2834]
lws compiled with -DLWS_WITH_DISTRO_RECOMMENDED=1

gdb ./lws-minimal-ws-broker
(gdb) run
Starting program: /libwebsockets/minimal-examples-lowlevel/ws-server/minimal-ws-broker/lws-minimal-ws-broker 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[2023/02/10 11:07:30:1886] U: LWS minimal ws broker | visit http://localhost:7681
[2023/02/10 11:07:30:1888] N: lws_create_context: LWS: 4.3.99-v4.3.0-276-ge8eb7d6b, NET CLI SRV H1 H2 WS MQTT SS-JSON-POL SSPROX ConMon IPV6-on
[2023/02/10 11:07:30:1889] N: __lws_lc_tag:  ++ [16380|wsi|0|pipe] (1)
[2023/02/10 11:07:30:1890] N: __lws_lc_tag:  ++ [16380|vh|0|netlink] (1)
[2023/02/10 11:07:30:1891] N: __lws_lc_tag:  ++ [16380|vh|1|default||7681] (2)
[2023/02/10 11:07:30:1892] N: [16380|vh|1|default||7681]: lws_socket_bind: source ads 0.0.0.0
[2023/02/10 11:07:30:1892] N: __lws_lc_tag:  ++ [16380|wsi|1|listen|default||7681] (2)
[2023/02/10 11:07:30:1893] N: [16380|vh|1|default||7681]: lws_socket_bind: source ads ::
[2023/02/10 11:07:30:1893] N: __lws_lc_tag:  ++ [16380|wsi|2|listen|default||7681] (3)
[2023/02/10 11:07:32:3962] N: __lws_lc_tag:  ++ [16380|wsisrv|0|default|(null)] (1)
[2023/02/10 11:07:32:4020] W: /mount-origin/index.html .zip/
[2023/02/10 11:07:32:4020] W: /mount-origin/index.html .jar/
[2023/02/10 11:07:32:4020] W: /mount-origin/index.html .war/
[2023/02/10 11:07:32:4020] W: /index.html .zip/
[2023/02/10 11:07:32:4021] W: /index.html .jar/
[2023/02/10 11:07:32:4021] W: /index.html .war/
[2023/02/10 11:07:32:4783] W: /mount-origin/example.js .zip/
[2023/02/10 11:07:32:4783] W: /mount-origin/example.js .jar/
[2023/02/10 11:07:32:4783] W: /mount-origin/example.js .war/
[2023/02/10 11:07:32:4783] W: /example.js .zip/
[2023/02/10 11:07:32:4783] W: /example.js .jar/
[2023/02/10 11:07:32:4783] W: /example.js .war/
[2023/02/10 11:07:32:5194] W: /mount-origin/libwebsockets.org-logo.svg .zip/
[2023/02/10 11:07:32:5194] W: /mount-origin/libwebsockets.org-logo.svg .jar/
[2023/02/10 11:07:32:5194] W: /mount-origin/libwebsockets.org-logo.svg .war/
[2023/02/10 11:07:32:5195] W: /libwebsockets.org-logo.svg .zip/
[2023/02/10 11:07:32:5195] W: /libwebsockets.org-logo.svg .jar/
[2023/02/10 11:07:32:5195] W: /libwebsockets.org-logo.svg .war/
[2023/02/10 11:07:32:5202] N: __lws_lc_tag:  ++ [16380|wsisrv|1|default|(null)] (2)
[2023/02/10 11:07:32:5205] W: /mount-origin/strict-csp.svg .zip/
[2023/02/10 11:07:32:5205] W: /mount-origin/strict-csp.svg .jar/
[2023/02/10 11:07:32:5205] W: /mount-origin/strict-csp.svg .war/
[2023/02/10 11:07:32:5205] W: /strict-csp.svg .zip/
[2023/02/10 11:07:32:5205] W: /strict-csp.svg .jar/
[2023/02/10 11:07:32:5205] W: /strict-csp.svg .war/
[2023/02/10 11:07:32:6100] N: __lws_lc_tag:  ++ [16380|wsisrv|2|default|(null)] (3)

Program received signal SIGSEGV, Segmentation fault.
0x0000555555564505 in callback_minimal (wsi=0x555555693730, reason=LWS_CALLBACK_ESTABLISHED, user=0x555555693e70, in=0x0, len=0)
    at /libwebsockets/minimal-examples-lowlevel/ws-server/minimal-ws-broker/protocol_lws_minimal.c:111
111                     pss->tail = lws_ring_get_oldest_tail(vhd->ring);
(gdb) bt
#0  0x0000555555564505 in callback_minimal (wsi=0x555555693730, reason=LWS_CALLBACK_ESTABLISHED, user=0x555555693e70, in=0x0, len=0)
    at /libwebsockets/minimal-examples-lowlevel/ws-server/minimal-ws-broker/protocol_lws_minimal.c:111
#1  0x00005555555bd1de in lws_server_init_wsi_for_ws (wsi=0x555555693730) at /projects/libwebsockets/lib/roles/ws/ops-ws.c:852
#2  0x00005555555c444b in lws_process_ws_upgrade2 (wsi=0x555555693730) at /projects/libwebsockets/lib/roles/ws/server-ws.c:405
#3  0x00005555555c4bc8 in lws_process_ws_upgrade (wsi=0x555555693730) at /projects/libwebsockets/lib/roles/ws/server-ws.c:634
#4  0x00005555555a7119 in lws_handshake_server (wsi=0x555555693730, buf=0x7fffffffd6d0, len=0) at /projects/libwebsockets/lib/roles/http/server/server.c:2501
#5  0x00005555555ac78c in lws_read_h1 (wsi=0x555555693730, 
    buf=0x55555568a81a "0 0.60388-0.22615 0.19247-0.22615 0.19247-0.73861v-1.3858h0.39938v2.6369h-0.32961l-0.0577-0.35367h-0.0217q-0.1227 0.19488-0.34163 0.29833-0.21653 0.10345-0.49561 0.10345-0.48118 0-0.72177-0.22856-0.23"..., len=586) at /projects/libwebsockets/lib/roles/h1/ops-h1.c:78
#6  0x00005555555ad258 in lws_h1_server_socket_service (wsi=0x555555693730, pollfd=0x55555568bca0) at /projects/libwebsockets/lib/roles/h1/ops-h1.c:447
#7  0x00005555555ad850 in rops_handle_POLLIN_h1 (pt=0x555555689c00, wsi=0x555555693730, pollfd=0x55555568bca0) at /projects/libwebsockets/lib/roles/h1/ops-h1.c:643
#8  0x000055555558b34a in lws_service_fd_tsi (context=0x555555689860, pollfd=0x55555568bca0, tsi=0) at /projects/libwebsockets/lib/core-net/service.c:766
#9  0x0000555555600e03 in _lws_plat_service_forced_tsi (context=0x555555689860, tsi=0) at /projects/libwebsockets/lib/plat/unix/unix-service.c:51
#10 0x000055555560124a in _lws_plat_service_tsi (context=0x555555689860, timeout_ms=2000000000, tsi=0) at /projects/libwebsockets/lib/plat/unix/unix-service.c:216
#11 0x00005555556012df in lws_plat_service (context=0x555555689860, timeout_ms=0) at /projects/libwebsockets/lib/plat/unix/unix-service.c:235
#12 0x000055555558b562 in lws_service (context=0x555555689860, timeout_ms=0) at /projects/libwebsockets/lib/core-net/service.c:838
#13 0x0000555555564aaa in main (argc=1, argv=0x7fffffffde08)
    at /libwebsockets/minimal-examples-lowlevel/ws-server/minimal-ws-broker/minimal-ws-broker.c:93

**Comment by ljluestc** [comment]
```

#include <libwebsockets.h>
#include <string.h>
#include <stdlib.h>

#define MAX_PAYLOAD_SIZE 1024

struct per_session_data {
    unsigned char buffer[MAX_PAYLOAD_SIZE];
    size_t len;
};

static int
callback_minimal(struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len)
{
    struct per_session_data *pss = (struct per_session_data *)user;

    switch (reason) {
    case LWS_CALLBACK_ESTABLISHED:
        lwsl_user("Connection established\n");

        // Initialize session data
        if (!pss) {
            lwsl_err("Session data is null\n");
            return -1; // Error: invalid user context
        }
        memset(pss->buffer, 0, MAX_PAYLOAD_SIZE);
        pss->len = 0;
        break;

    case LWS_CALLBACK_RECEIVE:
        lwsl_user("Received data: %.*s\n", (int)len, (char *)in);

        if (len > MAX_PAYLOAD_SIZE - 1) {
            lwsl_err("Payload size too large\n");
            return -1; // Error: payload too large
        }

        // Store received data
        memcpy(pss->buffer, in, len);
        pss->len = len;

        // Echo the data back to the client
        if (lws_write(wsi, pss->buffer, pss->len, LWS_WRITE_TEXT) < 0) {
            lwsl_err("Failed to send response\n");
            return -1; // Error: failed to send response
        }
        break;

    case LWS_CALLBACK_CLOSED:
        lwsl_user("Connection closed\n");
        break;

    default:
        break;
    }

    return 0;
}
```
