### ISSUE TITLE
Crashed when connect ws

### ISSUE THREAD

**Issue by nikohpng** [warmcat/libwebsockets#2859]
## Description
Server crashed When I connected to server

## Enviroment
- [x] libwebsockets-4.3.1

## Dump
```
#0  0x00007f3c383456bd in lws_buflist_next_segment_len () from /usr/local/lib/libwebsockets.so.19
#1  0x00007f3c383aa578 in rops_handle_POLLIN_ws () from /usr/local/lib/libwebsockets.so.19
#2  0x00007f3c3837e29f in lws_service_fd_tsi () from /usr/local/lib/libwebsockets.so.19
#3  0x00007f3c3833ab03 in _lws_plat_service_forced_tsi () from /usr/local/lib/libwebsockets.so.19
#4  0x00007f3c3833af59 in _lws_plat_service_tsi () from /usr/local/lib/libwebsockets.so.19
#5  0x00007f3c3833afbc in lws_plat_service () from /usr/local/lib/libwebsockets.so.19
#6  0x00007f3c3837e467 in lws_service () from /usr/local/lib/libwebsockets.so.19

```

## Code
```c
size_t
lws_buflist_next_segment_len(struct lws_buflist **head, uint8_t **buf)
{
	struct lws_buflist *b = (*head);

	if (buf)
		*buf = NULL;

	if (!b)
		return 0;	/* there is no next segment len */

	if (!b->len && b->next)
		if (lws_buflist_destroy_segment(head))
			return 0;

	b = (*head);
	if (!b)
		return 0;	/* there is no next segment len */

	assert(b->pos < b->len);

	if (buf)
		*buf = ((uint8_t *)b) + sizeof(*b) + b->pos + LWS_PRE;

	return b->len - b->pos;
}
```

**Comment by nikohpng** [comment]
this is second crash
```
#0  0x00007f3477707449 in malloc_consolidate () from /lib64/libc.so.6
#1  0x00007f34777090a5 in _int_malloc () from /lib64/libc.so.6
#2  0x00007f347770c6fc in malloc () from /lib64/libc.so.6
#3  0x00007f3410345284 in _realloc () from /usr/local/lib/libwebsockets.so.19
#4  0x00007f341034534e in lws_zalloc () from /usr/local/lib/libwebsockets.so.19
#5  0x00007f341037f62a in __lws_wsi_create_with_role () from /usr/local/lib/libwebsockets.so.19
#6  0x00007f341038324d in lws_create_new_server_wsi () from /usr/local/lib/libwebsockets.so.19
#7  0x00007f341038351e in __lws_adopt_descriptor_vhost1 () from /usr/local/lib/libwebsockets.so.19
#8  0x00007f3410384087 in lws_adopt_descriptor_vhost_via_info () from /usr/local/lib/libwebsockets.so.19
#9  0x00007f3410384013 in lws_adopt_descriptor_vhost () from /usr/local/lib/libwebsockets.so.19
#10 0x00007f34103b0a2d in rops_handle_POLLIN_listen () from /usr/local/lib/libwebsockets.so.19
#11 0x00007f341037e29f in lws_service_fd_tsi () from /usr/local/lib/libwebsockets.so.19
#12 0x00007f341033ab03 in _lws_plat_service_forced_tsi () from /usr/local/lib/libwebsockets.so.19
#13 0x00007f341033af59 in _lws_plat_service_tsi () from /usr/local/lib/libwebsockets.so.19
#14 0x00007f341033afbc in lws_plat_service () from /usr/local/lib/libwebsockets.so.19
#15 0x00007f341037e467 in lws_service () from /usr/local/lib/libwebsockets.so.19
#16 0x00007f34105f1f17 in janus_websockets_thread (data=0x26e0230) at transports/janus_websockets.c:1119
#17 0x00007f34791beabd in g_thread_proxy (data=0x26cd760) at ../subprojects/glib-2.64.2/glib/gthread.c:807
#18 0x00007f3477a5cea5 in start_thread () from /lib64/libpthread.so.0
#19 0x00007f34777858dd in clone () from /lib64/libc.so.6
```
