### ISSUE TITLE
Broken pipe.

### ISSUE THREAD

**Issue by marcin-stachowiak** [warmcat/libwebsockets#290]
I get sometimes "Broken pipe." error in my websocket server.
Bellow is a backtrace. In the line WebSocketServer.cpp:349 I have:
libwebsocket_service(context, 10); command.
Probably the error appear when client close connection...

Program received signal SIGPIPE, Broken pipe.
[Switching to Thread 0x7fffef6aa700 (LWP 2108)]
0x00007ffff798964c in send () from /lib/x86_64-linux-gnu/libpthread.so.0
(gdb) bt
#0  0x00007ffff798964c in send () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007ffff5d143c7 in EmbedSend () from /usr/local/lib/libcyassl.so.5
#2  0x00007ffff5d0f754 in SendBuffered () from /usr/local/lib/libcyassl.so.5
#3  0x00007ffff5d10bc1 in SendAlert () from /usr/local/lib/libcyassl.so.5
#4  0x00007ffff5d15714 in CyaSSL_shutdown () from /usr/local/lib/libcyassl.so.5
#5  0x00007ffff77733e2 in lws_ssl_close () from /usr/local/lib/libwebsockets.so.5
#6  0x00007ffff776c639 in libwebsocket_close_and_free_session () from /usr/local/lib/libwebsockets.so.5
#7  0x00007ffff776d03b in libwebsocket_service_fd () from /usr/local/lib/libwebsockets.so.5
#8  0x00007ffff7773918 in lws_plat_service () from /usr/local/lib/libwebsockets.so.5
#9  0x00000000004652a5 in WebSocketServer::run (this=0x6bed20) at /home/server/server/WebSocketServer.cpp:349
#10 0x000000000045c001 in Thread::threadFun (arg=0x6bed20) at /home/server/server/../libs/concurrency/Thread.hpp:36
#11 0x00007ffff7981b50 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#12 0x00007ffff6220e6d in clone () from /lib/x86_64-linux-gnu/libc.so.6
#13 0x0000000000000000 in ?? ()

**Comment by marcin-stachowiak** [comment]
I found the solution, problem is in the cyassl library.
SIGPIPE should be handled by the application.
So I can close the issue.
