### ISSUE TITLE
Assertion failed with address 'localhost' when the server is down

### ISSUE THREAD

**Issue by Slavasil** [warmcat/libwebsockets#2954]
Hello, I'm currently making a GTK+ (gtkmm) app in C++ and I decided to use this library as a websocket client. I made a c++ class for websocket handling and implemented the necessary routines to create lws_context, run a separate thread with a glib main loop and setting up the connection to the server (with the help of minimal-gtk and minimal-ws-client-ping examples). The problem is that, while debugging my program, at some point I got this message from libwebsockets (the last message before the program crashed):
``libwebsockets/lib/event-libs/glib/glib.c:268: elops_accept_glib: Assertion `!wsi_to_subclass(wsi)' failed.``
It is important to note that the program crashed only when the server was down.
Then I tried to look closely on the minimal gtk example and compare the code with mine, and did not found any substantial difference. The example works very well in its original form, but if the address of the server is changed to "localhost" or "something.localhost" it stops working properly and throws the same message if the server is not working. If the address is "127.0.0.1" or "::1" the example works as expected. I tested some other addresses but unfortunately I couldn't reproduce this situation. My operating system is Manjaro Linux with OpenSSL 3.1.1. To compile the example, I used the following command:
``gcc -Ilibwebsockets/build/include -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cloudproviders -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -pthread -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 main.c libwebsockets/build/lib/libwebsockets.a -lssl -lcrypto -lcap``

**Comment by lws-team** [comment]
What's the backtrace on the assert?

**Comment by Slavasil** [comment]
That's what I get from GDB:
```
#0  0x00007ffff689f26c in  () at /usr/lib/libc.so.6
#1  0x00007ffff684fa08 in raise () at /usr/lib/libc.so.6
#2  0x00007ffff6838538 in abort () at /usr/lib/libc.so.6
#3  0x00007ffff683845c in  () at /usr/lib/libc.so.6
#4  0x00007ffff68483d6 in  () at /usr/lib/libc.so.6
#5  0x00007ffff7f96a9e in elops_accept_glib (wsi=0x7fffec15cd20) at <project dir>/libwebsockets/lib/event-libs/glib/glib.c:268
#6  0x000055555557fe47 in lws_client_connect_3_connect ()
#7  0x000055555559ad42 in lws_http_client_socket_service ()
#8  0x000055555558e74f in rops_handle_POLLIN_h1 ()
#9  0x00007ffff5326034 in lws_service_fd_tsi (context=0x7fffec007cf0, pollfd=0x7ffff2ffe720, tsi=0) at <project dir>/libwebsockets/lib/core-net/service.c:766
#10 0x00007ffff7f96697 in lws_glib_dispatch (src=0x7fffec161a70, x=0x7ffff532614b <lws_service_fd>, userData=0x7fffec007cf0) at <project dir>/libwebsockets/lib/event-libs/glib/glib.c:142
#11 0x00007ffff7030a31 in g_main_dispatch (context=0x555555600a10) at ../glib/glib/gmain.c:3460
#12 g_main_context_dispatch (context=0x555555600a10) at ../glib/glib/gmain.c:4200
#13 0x00007ffff708dcc9 in g_main_context_iterate.isra.0 (context=0x555555600a10, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/glib/gmain.c:4276
#14 0x00007ffff702ffef in g_main_loop_run (loop=0x7fffec004900) at ../glib/glib/gmain.c:4479
#15 0x000055555555e961 in t1_main ()
#16 0x00007ffff7062d75 in g_thread_proxy (data=0x5555555faf00) at ../glib/glib/gthread.c:831
#17 0x00007ffff689d44b in  () at /usr/lib/libc.so.6
#18 0x00007ffff6920e40 in  () at /usr/lib/libc.so.6
```
