### ISSUE TITLE
null pointer dereference in pollfd.c when vhost is not defined

### ISSUE THREAD

**Issue by mulander** [warmcat/libwebsockets#568]
I'm testing 2.0.2 on a code base that used libwebsockets since v1.5 up to 1.7. Testing on OpenBSD/amd64 -current.

```c
        struct lws_client_connect_info i;
        struct lws *wsi_dumb;

        i.context = tsu->context;
        i.ssl_connection = use_ssl;
        i.address = wshost;
        i.port = wsport;
        i.host = wshost;
        i.origin = NULL;
        i.path = path;
        i.ietf_version_or_minus_one = ietf_version;
        i.protocol = protocols[PROTOCOL_TSUNAMI].name;
        i.client_exts = exts;
        // i.vhost = NULL;
        
        wsi_dumb = lws_client_connect_via_info(&i);
```

Note the commented out i.vhost. Uncommenting the line and setting vhost to NULL prevents the segfault from happening.

```
#0  0x00001816a4814595 in insert_wsi_socket_into_fds (context=0x1817634b4000, wsi=0x181735fe0000) at /usr/ports/pobj/libwebsockets-2.0.2/libwebsockets-2.0.2/lib/pollfd.c:139
139             if (wsi->vhost->protocols[0].callback(wsi, LWS_CALLBACK_LOCK_POLL,
(gdb) bt
#0  0x00001816a4814595 in insert_wsi_socket_into_fds (context=0x1817634b4000, wsi=0x181735fe0000) at /usr/ports/pobj/libwebsockets-2.0.2/libwebsockets-2.0.2/lib/pollfd.c:139
#1  0x00001816a481b74c in lws_client_connect_2 (wsi=0x181735fe0000) at /usr/ports/pobj/libwebsockets-2.0.2/libwebsockets-2.0.2/lib/client-handshake.c:167
#2  0x00001816a4817739 in lws_header_table_attach (wsi=0x181735fe0000, autoservice=0) at /usr/ports/pobj/libwebsockets-2.0.2/libwebsockets-2.0.2/lib/parsers.c:190
#3  0x00001816a481b0cd in lws_client_connect_via_info (i=0x1817300884c0) at /usr/ports/pobj/libwebsockets-2.0.2/libwebsockets-2.0.2/lib/client-handshake.c:576
#4  0x000018146470ad6f in tsunami_init () from /home/mulander/github/camcell/build-2.0.2/camcell
#5  0x000018146470a0ef in websocket_thread () from /home/mulander/github/camcell/build-2.0.2/camcell
#6  0x00001817341c793e in _rthread_start (v=Variable "v" is not available.
) at /usr/src/lib/librthread/rthread.c:115
#7  0x000018170216508b in __tfork_thread () at /usr/src/lib/libc/arch/amd64/sys/tfork_thread.S:75
#8  0x0000000000000000 in ?? ()
(gdb) p wsi->vhost
$1 = (struct lws_vhost *) 0x181464b16338
(gdb) p wsi->vhost->protocols
$2 = (const struct lws_protocols *) 0x0
(gdb) p wsi->vhost->protocols[0]
Cannot access memory at address 0x0

```

**Comment by mulander** [comment]
Sorry for the noise. This can be discarded I accidentally removed my memset 0 of the client info struct.
