### ISSUE TITLE
Segfault fetching static files with HTTP2/SSL

### ISSUE THREAD

**Issue by stlawrance** [warmcat/libwebsockets#979]
The following crash occurs fetching static files from lwsws using Firefox (wget works fine) and SSL:

```
Program received signal SIGSEGV, Segmentation fault.
lws_http2_parser (wsi=0x80281dc00, c=0 '\0') at lib/http2.c:237
237				wsi->u.http2.stream_wsi->u.http2.count = wsi->u.http2.count;
Current language:  auto; currently minimal
(gdb) bt
#0  lws_http2_parser (wsi=0x80281dc00, c=0 '\0') at lib/http2.c:237
#1  0x000000080082d1d6 in lws_read (wsi=0x80281dc00, buf=0x8028857e9 "", len=101) at lib/handshake.c:90
#2  0x00000008008357a1 in lws_service_fd_tsi (context=0x802841340, pollfd=0x7fffffff67d0, tsi=0) at lib/service.c:1205
#3  0x0000000800835a8f in lws_service_fd (context=0x802841340, pollfd=0x7fffffff67d0) at lib/service.c:1328
#4  0x000000080085ab63 in lws_io_cb (watcher=0x80281de00, status=0, revents=2) at lib/libuv.c:101
#5  0x000000080149029f in uv__io_poll () from /usr/local/lib/libuv.so.1
#6  0x0000000801481b18 in uv_run () from /usr/local/lib/libuv.so.1
#7  0x000000080085acb2 in lws_libuv_run (context=0x802841340, tsi=0) at lib/libuv.c:414
#8  0x0000000000401a4b in main (argc=1, argv=0x7fffffffea88) at lwsws/main.c:299
(gdb) print *wsi
$3 = {
  u = {
    http = {
      ah = 0x0, 
      ah_wait_list = 0x0, 
      preamble_rx = 0x0, 
      stash = 0x0, 
      preamble_rx_len = 0, 
      new_wsi_list = 0x0, 
      filepos = 0, 
      filelen = 0, 
      fop_fd = 0x0, 
      range = {
        start = 0, 
        end = 0, 
        extent = 0, 
        agg = 0, 
        budget = 0, 
        buf = 0x80281dc70 "", 
        pos = 0, 
        state = LWSRS_NO_ACTIVE_RANGE, 
        start_valid = 0 '\0', 
        end_valid = 0 '\0', 
        ctr = 0 '\0', 
        count_ranges = 0 '\0', 
        did_try = 0 '\0', 
        inside = 0 '\0', 
        send_ctr = 0 '\0'
      }, 
      multipart_content_type = 0x80281dd00 "", 
      request_version = HTTP_VERSION_1_0, 
      connection_type = HTTP_CONNECTION_CLOSE, 
      content_length = 0, 
      content_remain = 0
    }, 
    http2 = {
      http = {
        ah = 0x0, 
        ah_wait_list = 0x0, 
        preamble_rx = 0x0, 
        stash = 0x0, 
        preamble_rx_len = 0, 
        new_wsi_list = 0x0, 
        filepos = 0, 
        filelen = 0, 
        fop_fd = 0x0, 
        range = {
          start = 0, 
          end = 0, 
          extent = 0, 
          agg = 0, 
          budget = 0, 
          buf = 0x80281dc70 "", 
          pos = 0, 
          state = LWSRS_NO_ACTIVE_RANGE, 
          start_valid = 0 '\0', 
          end_valid = 0 '\0', 
          ctr = 0 '\0', 
          count_ranges = 0 '\0', 
          did_try = 0 '\0', 
          inside = 0 '\0', 
          send_ctr = 0 '\0'
        }, 
        multipart_content_type = 0x80281dd00 "", 
        request_version = HTTP_VERSION_1_0, 
        connection_type = HTTP_CONNECTION_CLOSE, 
        content_length = 0, 
        content_remain = 0
      }, 
      my_settings = {
        setting = 0x80281dd50
      }, 
      peer_settings = {
        setting = 0x80281dd6c
      }, 
      parent_wsi = 0x0, 
      next_child_wsi = 0x0, 
      hpack_dyn_table = 0x0, 
      stream_wsi = 0x0, 
      ping_payload = 0x80281dda8 "", 
      one_setting = 0x80281ddb0 "", 
      count = 1, 
      length = 5, 
      stream_id = 3, 
      hpack = HPKS_OPT_PADDING, 
      hpack_type = HPKT_INDEXED_HDR_7, 
      header_index = 0, 
      hpack_len = 0, 
      hpack_e_dep = 12517377, 
      tx_credit = 12582912, 
      my_stream_id = 0, 
      child_count = 0, 
      my_priority = 0, 
      END_STREAM = 0, 
      END_HEADERS = 0, 
      send_END_STREAM = 0, 
      GOING_AWAY = 0, 
      requested_POLLOUT = 1, 
      waiting_tx_credit = 0, 
      huff = 0, 
      value = 0, 
      round_robin_POLLOUT = 0, 
      count_POLLOUT_children = 0, 
      hpack_pos = 0, 
      type = 2 '\002', 
      flags = 0 '\0', 
      frame_state = 9 '\t', 
      padding = 0 '\0', 
      hpack_m = 0 '\0', 
      initialized = 1 '\001'
    }, 
    hdr = {
      ah = 0x0, 
      ah_wait_list = 0x0, 
      preamble_rx = 0x0, 
      stash = 0x0, 
      preamble_rx_len = 0, 
      ups = URIPS_IDLE, 
      ues = URIES_IDLE, 
      lextable_pos = 0, 
      current_token_limit = 0, 
      esc_stash = 0 '\0', 
      post_literal_equal = 0 '\0', 
      parser_state = 0 '\0'
    }, 
    ws = {
      hdr = {
        ah = 0x0, 
        ah_wait_list = 0x0, 
        preamble_rx = 0x0, 
        stash = 0x0, 
        preamble_rx_len = 0, 
        ups = URIPS_IDLE, 
        ues = URIES_IDLE, 
        lextable_pos = 0, 
        current_token_limit = 0, 
        esc_stash = 0 '\0', 
        post_literal_equal = 0 '\0', 
        parser_state = 0 '\0'
      }, 
      rx_ubuf = 0x0, 
      rx_ubuf_alloc = 0, 
      rx_draining_ext_list = 0x0, 
      tx_draining_ext_list = 0x0, 
      time_next_ping_check = 0, 
      rx_packet_length = 0, 
      rx_ubuf_head = 0, 
      mask = 0x80281dc6c "", 
      ping_payload_buf = 0x80281dc70 "", 
      ping_payload_len = 0 '\0', 
      mask_idx = 0 '\0', 
      opcode = 0 '\0', 
      rsv = 0 '\0', 
      rsv_first_msg = 0 '\0', 
      close_in_ping_buffer_len = 0 '\0', 
      utf8 = 0 '\0', 
      stashed_write_type = 0 '\0', 
      tx_draining_stashed_wp = 0 '\0', 
      final = 0, 
      frame_is_binary = 0, 
      all_zero_nonce = 0, 
      this_frame_masked = 0, 
      inside_frame = 0, 
      clean_buffer = 0, 
      payload_is_close = 0, 
      ping_pending_flag = 0, 
      continuation_possible = 0, 
      owed_a_fin = 0, 
      check_utf8 = 0, 
      defeat_check_utf8 = 0, 
      pmce_compressed_message = 0, 
      stashed_write_pending = 0, 
      rx_draining_ext = 0, 
      tx_draining_ext = 0, 
      send_check_ping = 0
    }
  }, 
  w_read = {
    uv_watcher = {
      data = 0x0, 
      loop = 0x602880, 
      type = UV_POLL, 
      close_cb = 0, 
      handle_queue = 0x80281de20, 
      u = {
        fd = 0, 
        reserved = 0x80281de30
      }, 
      next_closing = 0x0, 
      flags = 24576, 
      poll_cb = 0x80085aa70 <lws_io_cb>, 
      io_watcher = {
        cb = 0x801487a90 <uv_poll_init+176>, 
        pending_queue = 0x80281de70, 
        watcher_queue = 0x80281de80, 
        pevents = 5, 
        events = 5, 
        fd = 18, 
        rcount = 239, 
        wcount = 48994
      }
    }, 
    context = 0x802841340
  }, 
  pending_timeout_limit = 1500905098, 
  context = 0x802841340, 
  vhost = 0x802879000, 
  parent = 0x0, 
  child_list = 0x0, 
  sibling_list = 0x0, 
  protocol = 0x802823180, 
  same_vh_protocol_prev = 0x0, 
  same_vh_protocol_next = 0x0, 
  timeout_list = 0x0, 
  timeout_list_prev = 0x802841440, 
  access_log = {
    header_log = 0x0, 
    user_agent = 0x0, 
    sent = 0, 
    response = 0
  }, 
  user_space = 0x0, 
  rxflow_buffer = 0x8028857e0 "", 
  trunc_alloc = 0x0, 
  active_extensions = 0x80281df40, 
  act_ext_user = 0x80281df50, 
  ssl = 0x8028ba500, 
  client_bio = 0x0, 
  pending_read_list_prev = 0x0, 
  pending_read_list_next = 0x0, 
  desc = {
    sockfd = 18, 
    filefd = 18
  }, 
  position_in_fds_table = 1, 
  rxflow_len = 110, 
  rxflow_pos = 50, 
  trunc_alloc_len = 0, 
  trunc_offset = 0, 
  trunc_len = 0, 
  chunk_remaining = 0, 
  cache_secs = 0, 
  hdr_parsing_completed = 0, 
  http2_substream = 0, 
  listener = 0, 
  user_space_externally_allocated = 0, 
  socket_is_permanently_unusable = 0, 
  rxflow_change_to = 3, 
  more_rx_waiting = 0, 
  conn_stat_done = 0, 
  cache_reuse = 0, 
  cache_revalidate = 0, 
  cache_intermediaries = 0, 
  favoured_pollin = 0, 
  sending_chunked = 0, 
  already_did_cce = 0, 
  told_user_closed = 0, 
  access_log_pending = 0, 
  do_ws = 0, 
  chunked = 0, 
  client_rx_avail = 0, 
  client_http_body_pending = 0, 
  extension_data_pending = 0, 
  use_ssl = 1, 
  redirect_to_https = 0, 
  handling_pollout = 0, 
  leave_pollout_active = 0, 
  c_port = 0, 
  count_act_ext = 0 '\0', 
  ietf_spec_revision = 0 '\0', 
  mode = 5 '\005', 
  state = 14 '\016', 
  state_pre_close = 0 '\0', 
  lws_rx_parse_state = 0 '\0', 
  rx_frame_type = 0 '\0', 
  pending_timeout = 3 '\003', 
  pps = 0 '\0', 
  tsi = 0 '\0', 
  protocol_interpret_idx = 0 '\0', 
  redirects = 0 '\0', 
  chunk_parser = 0 '\0', 
  reason_bf = 0 '\0'
}

(gdb) print wsi->state
$4 = 14 '\016'
== LWSS_HTTP2_ESTABLISHED

(gdb) print wsi->u.http2.type
$5 = 2 '\002'
== LWS_HTTP2_FRAME_TYPE_PRIORITY

(gdb) print wsi->u.http2.count
$6 = 1
```

**Comment by lws-team** [comment]
Thanks.

Sorry, but HTTP/2 support in lws is incomplete.

Basically, the Powers That Be decided they will not implement websockets in http/2.  Their "solution" is if you want websockets, you must do it over http/1.x.  There are no standardized arrangements to tunnel it either.  (That is very strange, because TPTB took care of every other aspect of http/1 support in http/2 EXCEPT ws.  And it's obvious ws is more popular than ever right now.  But for those guys, ws is somehow too shitty to bother themselves with and the official answer is "let them eat http/1 cake" / go discuss it on a dead mailing list to no result.)

Therefore the risk I took a couple of years ago adding basic - to the point I could transfer a file - http/2 support while ws was argued out on TPTB's mailing list is stuck, because there is no way to bring it to a conclusion that supports ws.  For that reason, considering it's "libwebsockets" and http is an add-on, I don't intend to pour any more work into it (it took many weeks of my time already.... getting anything to actually transport on http/2 is a major undertaking) until / unless something changes.

For a while how it is waiting for some change at the standards level was a reasonable situation but I think it's time to remove the HTTP/2 cmake option.  I'll leave the code in for a bit longer in case something changes.

**Comment by stlawrance** [comment]
Thanks for the detailed answer; I wasn't aware of the situation with WS and HTTP/2 at all.  I didn't have any good reason to enable the option other than to just try it out anyway...
